import { StyleSheet } from "react-native";

// Design tokens: colors, layout, spacing, sizes, typography, shadows.
export const colors = {
  inputBg: "rgba(6, 28, 18, 0.55)",
  border: "rgba(255, 255, 255, 0.55)",
  borderMuted: "rgba(255, 255, 255, 0.35)",
  text: "#FFFFFF",
  textMuted: "rgba(255, 255, 255, 0.72)",
  textSecondary: "rgba(255, 255, 255, 0.85)",
  accent: "#C6F54B",
  buttonText: "#ACDB60",
  backArrow: "#ADDC60",
  tabBarInactive: "#749340",
  resetButtonBorder: "#FF0001",
  profileDeleteAccount: "rgba(173, 220, 96, 0.15)",
  supportHeader: "#C5BF16",
  supportOkInactive: "#918C11",
  legalLink: "#E2F163",
  inputFill: "#FFFFF1",
  workoutGlassCardFill: "rgba(255, 255, 241, 0.2)",
  inputText: "#171D1C",
  inputPlaceholder: "#232323",
  white: "#FFFFFF",
  profileCameraIcon: "#D2D2D2",
  doExerciseCircle: "#D9D9D9",
  black: "#000000",
  buttonBorder: "#EDEBDF",
  errorBorder: "#A40000",
  surface: "transparent",
  divider: "rgba(255, 255, 255, 0.2)",
  backdrop: "rgba(6, 28, 18, 0.7)",
  modalSurface: "#0F2A1C",
  background: "#171D1C",
  cardSurface: "rgba(255, 255, 255, 0.04)",
  cardBorder: "rgba(255, 255, 255, 0.04)",
  errorCardTint: "rgba(255, 0, 0, 0.04)",
  supportCardTint: "rgba(197, 191, 22, 0.04)",
  successCardTint: "rgba(173, 220, 96, 0.04)",
  genderMale: "#007BEE",
  genderFemale: "#EE00CE",
  sportsExperienceBeginner: "#ADDC60",
  sportsExperienceGymRat: "#5FBFF9",
  sportsExperienceBeastMode: "#FF0001",
  skipLink: "rgba(173, 220, 96, 0.5)",
  shadow: "#000000",
  weekCalendarDay: "#B8E65A",
  weekCalendarDayText: "#222222",
  workoutSetW: "#FFC300",
  workoutSetWorking: "#0F7D20",
  setFeelingHard: "#E6B616",
  workoutLastWorkout: "rgba(255, 255, 241, 0.5)",
  saveExerciseOverlay: "rgba(23, 29, 28, 0.1)",
  menuOverlayProLink: "#16BAC5",
} as const;

export const layout = {
  authMaxWidth: 420,
  authCardBleed: -10,
  authFormSideInset: -8,
  authCardRadius: 30,
  screenPaddingHorizontal: 24,
  appleButtonRadius: 10,
} as const;

export const spacing = {
  authBackTitleDefault: 69,
  authBackTitleSuccess: 109,
  authBackTitleNewPassword: 76,
  authBackTitleWeight: 114,
  authBackTitleAge: 131,
  authBackTitleHeight: 117,
  authBackTitleSupportSubmitted: 97,
  authBackTitleError: 122,
  authBackTitleSupportError: 126,
  authBackTitleContactUs: 110,
  authBackTitleSportsExperience: 60,
  authBackTitleVerifyEmail: 90,
  signInHeader: 214,
  verifyEmailHeader: 180,
  verifyEmailForm: 48,
  signInForm: 60,
  signUpHeader: 80,
  signUpLegal: 45,
  signUpPostHeader: 18,
  forgotPasswordHeader: 217,
  forgotPasswordForm: 202,
  newPasswordHeader: 214,
  newPasswordForm: 117,
  genderHeaderToButtons: 446,
  weightHeader: 194,
  weightUnitToggleScreenInset: 38,
  weightToggleToRuler: 52,
  weightRulerNumberToBar: 5,
  weightRulerToReadout: 5,
  weightRulerReadoutArrowToValue: 19,
  weightRulerReadoutValueLeftGap: 136,
  weightRulerReadoutUnitGap: 4,
  weightReadoutToNext: 38,
  ageReadoutToWheel: 93,
  ageWheelRulerToArrow: 28,
  ageHeaderToSelection: 198,
  ageSelectionToNext: 165,
  heightHeaderToReadout: 67,
  heightRulerNumberToBar: 5,
  heightReadoutToRuler: 16,
  heightRulerNeedlePointerGap: 6,
  heightReadoutToNext: 38,
  genderForm: 94,
  sportsExperienceHeaderToOptions: 199,
  sportsExperienceOptions: 36,
  genderOptions: 65,
  genderOptionsScreenInset: 14,
  successHeader: 302,
  successBody: 206,
  successActions: 18,
  supportResultBody: 216,
  contactUsHeader: 80,
  contactUsForm: 56,
  errorFormActions: 22,
  errorContact: 21,
  fieldStack: 13,
  cardFields: 16,
  socialGroup: 17,
  orSignWith: 11,
  forgotPasswordLink: 12,
  contactHelpTitleBottom: 16,
  cardGap: 14,
  formGap: 14,
  tabContent: 16,
  workoutGreetingLeft: 16,
  workoutUserNameLeft: 27,
  workoutGlassCardsInset: 16,
  workoutGlassCardsGap: 11,
  workoutNameToGlassCards: 6,
  workoutGlassCardsToWide: 16,
  workoutGlassCardValueToLabel: 1,
  workoutWeekCalendarTop: 16,
  weekCalendarDayGap: 4,
  weekCalendarWeekdayToDate: 5,
  weekCalendarTodayElevate: 10,
  workoutStartTrainingTop: 15,
  workoutTrainingProgramsTop: 26,
  workoutMyProgramsTop: 7,
  workoutMyProgramsToCreateButton: 10,
  workoutSelectedProgramToButton: 7,
  workoutSelectedProgramButtonToDay: 10,
  workoutSelectedProgramButtonTextLeft: 47,
  workoutSelectedProgramButtonToGreenBar: 16,
  startWorkoutHeaderToYourPrograms: 14,
  startWorkoutYourProgramsToPreset: 20,
  programDayHeaderToProgramName: 14,
  programDayProgramNameLeft: 23,
  programDayProgramNameToLine: 10,
  programDayLineToDay: 13,
  programDayDayLabelLeft: 76,
  programDayBackLeft: 35,
  programDayEditTop: 41,
  programDayExerciseHeaderToCircle: 30,
  programDayExerciseSelectDaySide: 69,
  startWorkoutProgramButtonTitleToSubtitle: 4,
  startWorkoutProgramButtonLinkLeft: 20,
  startWorkoutProgramButtonStartRight: 20,
  historyButtonTextLeft: 57,
  historyButtonTextRight: 57,
  createProgramCardInset: 30,
  createProgramHeaderToCard: 236,
  createProgramCardToNext: 36,
  createDayHeaderToBar: 30,
  workoutHeaderToBar: 36,
  addExerciseHeaderToButtons: 30,
  doExerciseCirclesLeft: 20,
  doExerciseCirclesGap: 10,
  addExerciseBarToExercises: 30,
  doExerciseCircleToName: 47,
  doExerciseLinkRight: 19,
  exerciseHistoryHeaderToImage: 30,
  exerciseHistoryImageToHistory: 14,
  exerciseHistoryLabelLeft: 18,
  exerciseHistoryLabelToButtons: 14,
  exerciseHistoryButtonsGap: 10,
  exerciseHistoryButtonsInset: 41,
  exerciseHistoryButtonDateLeft: 20,
  exerciseHistoryButtonTextGap: 14,
  createDayBurgerRight: 21,
  saveToBurger: 25,
  programDayExerciseTimerIconToText: 8,
  programDayExerciseAddToTimers: 199,
  programDayExerciseClockLeft: 62,
  programDayExerciseStopwatchRight: 62,
  createDayAccentBarLabelLeft: 16,
  workoutAccentBarLabelLeft: 35,
  workoutSetHeadersSide: 35,
  workoutSetStatusBarLeft: 16,
  workoutBarToSetHeaders: 13,
  workoutSetHeadersToLine: 13,
  workoutLineToSetValues: 14,
  workoutLastLineToLastWorkout: 13,
  workoutLastWorkoutRight: 16,
  workoutLastWorkoutToAddSet: 95,
  workoutAddSetToTimers: 159,
  setScreenRecordToDropSet: 93,
  setScreenHeaderToWeight: 36,
  setScreenWeightLabelToValue: 15,
  setScreenWeightValueToLine: 25,
  setScreenWeightLabelToChevron: 4,
  setScreenLineToFeeling: 20,
  setScreenFeelingLabelToBar: 20,
  setScreenFeelingToRecord: 103,
  dropSetBarToWeight: 7,
  dropSetLineToAddDrop: 30,
  dropSetAddDropToFeeling: 80,
  dropSetFeelingToRecord: 30,
  saveExerciseOverlayTop: 299,
  saveExerciseButtonToCancel: 30,
  addExerciseToDayLabelTop: 34,
  addExerciseAddDayBarTop: 34,
  addExerciseDayRecordTop: 34,
  addExerciseSaveTop: 361,
  workoutProgramStartIconRight: 16,
  workoutProgramExternalLinkIconLeft: 16,
  workoutProgramIconToText: 20,
  workoutProgramSubtitleMetaGap: 16,
  workoutProfileButtonRight: 16,
  workoutBellToProfile: 16,
  menuOverlayHeaderTop: 39,
  menuOverlayHeaderHorizontal: 16,
  menuIconToLabel: 8,
  progressScreenBottom: 24,
  progressHeaderToContent: 30,
  progressSectionLabelToRows: 10,
  progressSectionGap: 20,
  progressMuscleScrollBottom: 24,
  progressMetricDiagramTop: 30,
  progressMetricDiagramInset: 16,
  progressMetricHistoryTop: 30,
  progressMetricRecordTop: 30,
  progressMetricDetailHistoryTop: 20,
  profileAvatarTop: 21,
  profileAvatarToUploadLabel: 24,
  profileUploadToButtons: 20,
  profileActionButtonGap: 10,
  profileActionButtonInset: 41,
  profileActionButtonTextLeft: 16,
  profileButtonsToConnectors: 40,
  profileConnectorsToItems: 23,
  profileConnectorItemGap: 10,
  profileConnectorGarminStatusNudge: 6,
  profileConnectorsToLogOut: 40,
  profileLogOutToDeleteAccount: 40,
  profileDeleteAccountBottom: 20,
  profileFieldSheetCardToButton: 36,
  profileFieldSheetTop: 34,
  profileBirthdaySheetBottom: 13,
  profileAvatarInnerTop: 148,
  profileAvatarInnerLeft: 220,
  safeAreaTopMin: 12,
  safeAreaTopExtra: 4,
  safeAreaBottomMin: 8,
  authSkipLinkVertical: 12,
  authSkipLinkBottom: 6,
  authSkipToNext: 37,
  swipeActiveOffsetX: 20,
  swipeBackTranslation: 72,
  swipeBackFastTranslation: 40,
  swipeBackVelocity: 600,
} as const;

export const sizes = {
  authInputHeight: 45,
  authButtonHeight: 60,
  authButtonPressDuration: 180,
  weightUnitToggleHeight: 60,
  weightRulerStepWidth: 10,
  weightRulerMajorLabelWidth: 104,
  weightRulerMin: 40,
  weightRulerMax: 200,
  weightRulerDefault: 75,
  weightRulerStep: 1,
  weightRulerBarHeight: 87,
  weightRulerNumberRowHeight: 48,
  weightRulerTickMinorHeight: 24,
  weightRulerTickMinorWidth: 1,
  weightRulerTickHalfHeight: 46,
  weightRulerTickHalfWidth: 2,
  weightRulerTickMajorHeight: 46,
  weightRulerTickMajorWidth: 2,
  weightRulerNeedleWidth: 2,
  weightRulerNeedleHeight: 56,
  weightRulerSelectedScale: 1,
  weightRulerAdjacentScale: 1,
  weightRulerFarScale: 1,
  weightRulerAdjacentOpacity: 0.65,
  authReadoutArrowWidth: 46,
  authReadoutArrowHeight: 32,
  authReadoutArrowRadius: 4,
  authReadoutArrowScale: 1,
  weightRulerReadoutUnitOffset: 10,
  ageWheelMin: 13,
  ageWheelMax: 100,
  ageWheelDefault: 28,
  ageWheelSegmentWidth: 70,
  ageWheelSelectionFrameWidth: 87,
  ageWheelBannerHeight: 87,
  ageWheelSelectedBorderWidth: 2,
  ageWheelSelectedLabelNudge: 2,
  ageWheelSelectedScale: 1,
  ageWheelAdjacentScale: 0.86,
  ageWheelAdjacentOpacity: 0.65,
  ageWheelFarOpacity: 0.45,
  ageWheelFarScale: 0.72,
  heightRulerMin: 100,
  heightRulerMax: 250,
  heightRulerDefault: 170,
  heightRulerStep: 1,
  heightRulerStepHeight: 10,
  heightRulerBarWidth: 87,
  heightRulerBarRadius: 10,
  heightRulerNumberColumnWidth: 104,
  heightRulerViewportHeight: 371,
  heightRulerTickMinorWidth: 24,
  heightRulerTickMinorHeight: 1,
  heightRulerTickHalfWidth: 46,
  heightRulerTickHalfHeight: 2,
  heightRulerTickMajorWidth: 46,
  heightRulerTickMajorHeight: 2,
  heightRulerNeedleWidth: 56,
  heightRulerNeedleHeight: 2,
  heightRulerReadoutUnitOffset: 10,
  genderOptionMaleButtonWidth: 189,
  genderOptionButtonHeight: 60,
  signInCardBlurIntensity:15,
  workoutGlassBlurIntensity: 80,
  saveExerciseBlurIntensity: 40,
  authResultCardHeight: 57,
  successCardIcon: 33,
  contactTextAreaHeight: 235,
  googleIcon: 40,
  workoutProfileButton: 44,
  menuOverlayPanelHeight: 400,
  menuOverlayTabBarReserve: 56,
  menuFigmaWidth: 393,
  menuIconSize: 40,
  menuGridItemWidth: 96,
  menuGridIconTop: 94,
  menuGridSecondIconTop: 204,
  menuGridCalculatorLeft: 28,
  menuGridProgressLeft: 178,
  menuGridProgramsLeft: 330,
  menuGridNotificationsLeft: 104,
  menuGridSettingsLeft: 259,
  menuBellIconWidth: 30.85,
  menuBellIconHeight: 29.2,
  progressMetricDiagramHeight: 174,
  workoutBellWidth: 19,
  workoutBellHeight: 18,
  workoutBellBadge: 10,
  workoutStartIconWidth: 19,
  workoutStartIconHeight: 18,
  workoutExternalLinkIcon: 18,
  workoutProgramThinBorderWidth: 1,
  programDayDividerHeight: 1,
  createDayAccentBarHeight: 24,
  workoutAccentBarHeight: 44,
  workoutSetStatusBarWidth: 3,
  workoutSetRowHeight: 48,
  workoutDropSetGroupHeight: 126,
  doExerciseCircle: 54,
  exerciseHistoryImageWidth: 361,
  exerciseHistoryImageHeight: 180,
  createDayBurgerWidth: 18,
  createDayBurgerHeight: 14,
  saveIconWidth: 24,
  saveIconHeight: 24,
  saveIconStroke: 2,
  setScreenPlusIcon: 24,
  setScreenChevronWidth: 6,
  setScreenChevronHeight: 3,
  setScreenFeelingBarBorder: 1,
  programDayExerciseTimerIcon: 18,
  workoutGlassCardHeight: 65,
  workoutGlassCardWideHeight: 120,
  workoutGlassCardRadius: 22,
  workoutStartTrainingBarHeight: 50,
  weekCalendarDayWidth: 43,
  weekCalendarSelectedWidth: 79,
  weekCalendarDayHeight: 60,
  weekCalendarDayRadius: 12,
  weekCalendarActivityDot: 6,
  weekCalendarSelectedBorderWidth: 1.5,
  weekCalendarDayPaddingVertical: 10,
  weekCalendarAnimDuration: 220,
  weekCalendarSelectedElevation: 3,
  profileAvatar: 160,
  profileAvatarInner: 40,
  profileAvatarCameraWidth: 53,
  profileAvatarCameraHeight: 44,
  profileAvatarPlus: 15.5,
  profileAvatarPlusStroke: 2,
  profileActionButtonHeight: 45,
  profileActionButtonChevronWidth: 5,
  profileActionButtonChevronHeight: 9,
  profileFieldSheetHeight: 260,
  backArrowHitSlop: 12,
  backArrowRowMinHeight: 40,
  backArrowRowMarginLeft: 11,
  backArrowTriangleSlotWidth: 12,
  backArrowTriangleSlotHeight: 16,
  backArrowTriangleBorder: 8,
  backArrowTriangleWidth: 12,
  authInputRadius: 15,
  authButtonRadius: 100,
  authCardPaddingTop: 18,
  authCardPaddingBottom: 24,
  authCardPaddingLeft: 24,
  authCardPaddingRight: 26,
  forgotPasswordCardPaddingBottom: 45,
  newPasswordCardPaddingBottom: 39,
  contactUsCardPaddingBottom: 14,
  textAreaPaddingVertical: 12,
} as const;

export const typography = {
  tabLabel: {
    fontSize: 10,
  },
  workoutGreeting: {
    fontSize: 16,
  },
  workoutUserName: {
    fontSize: 26,
  },
  workoutGlassCardValue: {
    fontSize: 32,
  },
  workoutGlassCardLabel: {
    fontSize: 10,
  },
  weekCalendarWeekday: {
    fontSize: 10,
  },
  weekCalendarDayNumber: {
    fontSize: 10,
  },
  weekCalendarSelectedDayNumber: {
    fontSize: 10,
  },
  weekCalendarTodayLabel: {
    fontSize: 6,
  },
  workoutMyPrograms: {
    fontSize: 10,
  },
  workoutSetValueExponent: {
    fontSize: 6,
  },
  menuOverlayTitle: {
    fontSize: 10,
  },
  menuOverlayProLink: {
    fontSize: 10,
  },
  menuGridLabel: {
    fontSize: 10,
  },
  progressSectionLabel: {
    fontSize: 10,
  },
  progressMetricDiagramLabel: {
    fontSize: 9,
  },
  progressMetricHistoryDate: {
    fontSize: 14,
  },
  progressMetricHistoryValue: {
    fontSize: 14,
  },
  progressMetricRecordButtonText: {
    fontSize: 10,
  },
  createDayAccentBarLabel: {
    fontSize: 10,
  },
  addExerciseToDayLabel: {
    fontSize: 10,
  },
  programDayExerciseTimerText: {
    fontSize: 13,
  },
  exerciseHistoryLabel: {
    fontSize: 10,
  },
  exerciseHistoryButtonDate: {
    fontSize: 10,
  },
  exerciseHistoryButtonWeight: {
    fontSize: 10,
  },
  doExerciseName: {
    fontSize: 14,
  },
  workoutProgramFilledButtonText: {
    fontSize: 16,
  },
  startWorkoutProgramButtonText: {
    fontSize: 16,
    lineHeight: 18,
  },
  startWorkoutProgramButtonSubtitle: {
    fontSize: 10,
    lineHeight: 12,
  },
  workoutStartTrainingGreenBarText: {
    fontSize: 18,
  },
  workoutBellBadgeText: {
    fontSize: 8,
  },
  profileUploadPhoto: {
    fontSize: 10,
  },
  profileConnectors: {
    fontSize: 10,
  },
  profileConnectorItem: {
    fontSize: 10,
  },
  profileLogOut: {
    fontSize: 10,
  },
  profileDeleteAccount: {
    fontSize: 10,
  },
  authTitle: {
    fontSize: 20,
    lineHeight: 28,
  },
  authLabel: {
    fontSize: 18,
    lineHeight: 22,
  },
  authSmall: {
    fontSize: 14,
    lineHeight: 18,
  },
  authButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  authInput: {
    fontSize: 16,
    lineHeight: 20,
  },
  authLink: {
    fontSize: 16,
    lineHeight: 20,
  },
  authSkip: {
    fontSize: 15,
    lineHeight: 18,
  },
  weightRulerSelectedNumber: {
    fontSize: 40,
    lineHeight: 48,
  },
  weightRulerAdjacentNumber: {
    fontSize: 35,
    lineHeight: 42,
  },
  weightRulerReadoutValue: {
    fontSize: 64,
    lineHeight: 80,
  },
  weightRulerReadoutUnit: {
    fontSize: 18,
    lineHeight: 22,
  },
  ageWheelSelectedNumber: {
    fontSize: 40,
    lineHeight: 48,
  },
  ageWheelAdjacentNumber: {
    fontSize: 35,
    lineHeight: 35,
  },
  ageWheelFarNumber: {
    fontSize: 25,
    lineHeight: 25,
  },
  ageWheelReadoutValue: {
    fontSize: 64,
    lineHeight: 80,
  },
  heightRulerReadoutValue: {
    fontSize: 64,
    lineHeight: 80,
  },
  sportsExperienceOptionButton: {
    fontSize: 24,
    lineHeight: 28,
  },
} as const;

export const shadows = {
  authCard: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8.1,
    elevation: 4,
  },
  profileFieldSheet: {
    shadowColor: colors.backArrow,
    shadowOffset: { width: 0, height: -22 },
    shadowOpacity: 1,
    shadowRadius: 70.9,
    elevation: 0,
  },
  weekCalendarSelected: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
} as const;

export const fonts = {
  montserratExtraLight: "Montserrat_200ExtraLight",
  montserratLight: "Montserrat_300Light",
  montserratRegular: "Montserrat_400Regular",
  montserratMedium: "Montserrat_500Medium",
  montserratBold: "Montserrat_700Bold",
  poppinsLight: "Poppins_300Light",
  poppinsRegular: "Poppins_400Regular",
  poppinsMedium: "Poppins_500Medium",
  poppinsSemiBold: "Poppins_600SemiBold",
  poppinsBold: "Poppins_700Bold",
  leagueSpartanLight: "LeagueSpartan_300Light",
  leagueSpartanMedium: "LeagueSpartan_500Medium",
  leagueSpartanBold: "LeagueSpartan_700Bold",
} as const;

const authScreenBase = {
  flex: 1,
  width: "100%" as const,
  maxWidth: layout.authMaxWidth,
  alignSelf: "center" as const,
  minHeight: "100%" as const,
};

const authInputsCardBase = {
  alignSelf: "stretch" as const,
  borderRadius: layout.authCardRadius,
  backgroundColor: colors.cardSurface,
  borderWidth: 1,
  borderColor: colors.cardBorder,
  overflow: "hidden" as const,
  paddingTop: sizes.authCardPaddingTop,
  paddingLeft: sizes.authCardPaddingLeft,
  paddingRight: sizes.authCardPaddingRight,
  paddingBottom: sizes.authCardPaddingBottom,
};

const authBleedStretch = {
  alignSelf: "stretch" as const,
  marginHorizontal: layout.authCardBleed,
};

const supportOkTextBase = {
  ...typography.authTitle,
  fontFamily: fonts.leagueSpartanBold,
  fontWeight: "700" as const,
  textAlign: "center" as const,
  includeFontPadding: false,
};

export const globalStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    flexGrow: 1,
    paddingHorizontal: layout.screenPaddingHorizontal,
    paddingTop: 8,
    paddingBottom: 28,
  },
  screenBody: {
    flex: 1,
    width: "100%",
    maxWidth: layout.authMaxWidth,
    alignSelf: "center",
  },
  tabScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  tabScreenContent: {
    alignItems: "center",
    gap: spacing.tabContent,
  },
  tabScreenText: {
    ...typography.authTitle,
    color: colors.black,
    textAlign: "center",
  },
  tabBarLabel: {
    ...typography.tabLabel,
    color: colors.tabBarInactive,
    fontFamily: fonts.montserratLight,
    fontWeight: "300",
  },
  tabBarLabelActive: {
    ...typography.tabLabel,
    color: colors.backArrow,
    fontFamily: fonts.montserratLight,
    fontWeight: "300",
  },
  createProgramScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  createProgramScreenBody: {
    ...authScreenBase,
  },
  addExerciseScreenScroll: {
    flex: 1,
  },
  addExerciseScreenScrollContent: {
    flexGrow: 1,
  },
  addExerciseActionButtons: {
    alignSelf: "stretch",
    marginTop: spacing.addExerciseHeaderToButtons,
    paddingHorizontal: spacing.profileActionButtonInset,
    gap: spacing.profileActionButtonGap,
  },
  addExerciseActionButton: {
    alignSelf: "stretch",
    height: sizes.profileActionButtonHeight,
    borderRadius: sizes.authInputRadius,
    backgroundColor: colors.inputFill,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.profileActionButtonTextLeft,
    paddingRight: spacing.profileActionButtonTextLeft,
    gap: spacing.profileActionButtonTextLeft,
  },
  customExerciseImageButton: {
    alignSelf: "stretch",
    height: sizes.doExerciseCircle,
    borderRadius: sizes.authInputRadius,
    backgroundColor: colors.inputFill,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.profileActionButtonTextLeft,
    paddingRight: spacing.profileActionButtonTextLeft,
    gap: spacing.profileActionButtonTextLeft,
  },
  customExerciseImageThumb: {
    width: sizes.doExerciseCircle,
    height: sizes.doExerciseCircle,
    borderRadius: sizes.doExerciseCircle / 2,
    overflow: "hidden",
    flexShrink: 0,
  },
  customExerciseImageThumbImage: {
    width: sizes.doExerciseCircle,
    height: sizes.doExerciseCircle,
  },
  exerciseMuscleGroupButton: {
    alignSelf: "stretch",
    height: sizes.profileActionButtonHeight,
    borderRadius: sizes.authInputRadius,
    backgroundColor: colors.backArrow,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.profileActionButtonTextLeft,
    paddingRight: spacing.profileActionButtonTextLeft,
    gap: spacing.profileActionButtonTextLeft,
  },
  doExerciseCirclesRow: {
    flexDirection: "column",
    alignSelf: "stretch",
    marginTop: spacing.addExerciseHeaderToButtons,
    paddingLeft: spacing.doExerciseCirclesLeft,
    gap: spacing.doExerciseCirclesGap,
  },
  doExerciseItem: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    paddingRight: spacing.doExerciseLinkRight,
  },
  historyDayExerciseSwipe: {
    alignSelf: "stretch",
  },
  historyDayExerciseSwipeChildren: {
    backgroundColor: colors.background,
  },
  historySwipeDelete: {
    width: spacing.swipeBackTranslation,
    backgroundColor: colors.resetButtonBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  historySwipeDeleteText: {
    ...typography.doExerciseName,
    color: colors.inputFill,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  doExerciseSelectTarget: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.doExerciseCircleToName,
  },
  doExerciseCircle: {
    width: sizes.doExerciseCircle,
    height: sizes.doExerciseCircle,
    borderRadius: sizes.doExerciseCircle / 2,
    backgroundColor: colors.doExerciseCircle,
    flexShrink: 0,
  },
  doExerciseName: {
    ...typography.doExerciseName,
    flex: 1,
    color: colors.white,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  exerciseHistoryImage: {
    marginTop: spacing.exerciseHistoryHeaderToImage,
  },
  exerciseHistoryLabel: {
    ...typography.exerciseHistoryLabel,
    marginTop: spacing.exerciseHistoryImageToHistory,
    paddingLeft: spacing.exerciseHistoryLabelLeft,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
  },
  exerciseHistoryButtonsRow: {
    alignSelf: "stretch",
    width: "100%",
    flexDirection: "column",
    marginTop: spacing.exerciseHistoryLabelToButtons,
    gap: spacing.exerciseHistoryButtonsGap,
  },
  exerciseHistoryButton: {
    alignSelf: "stretch",
    marginHorizontal: spacing.exerciseHistoryButtonsInset,
    alignItems: "center",
    paddingLeft: spacing.exerciseHistoryButtonDateLeft,
    paddingRight: spacing.exerciseHistoryButtonDateLeft,
    gap: 0,
  },
  exerciseHistoryButtonDate: {
    ...typography.exerciseHistoryButtonDate,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    color: colors.inputFill,
    includeFontPadding: false,
  },
  exerciseHistoryButtonContent: {
    flex: 1,
    gap: spacing.exerciseHistoryButtonTextGap,
  },
  exerciseHistoryButtonRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.exerciseHistoryButtonTextGap,
  },
  exerciseHistoryButtonSpacer: {
    flexGrow: 0,
    flexShrink: 0,
    width: 0,
    fontSize: 0,
    lineHeight: 0,
  },
  exerciseHistoryButtonProgram: {
    ...typography.exerciseHistoryButtonDate,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    color: colors.inputFill,
    includeFontPadding: false,
    textAlign: "right",
  },
  exerciseHistoryButtonWeight: {
    ...typography.exerciseHistoryButtonWeight,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    textAlign: "right",
  },
  createProgramCardWrap: {
    marginHorizontal: spacing.createProgramCardInset,
  },
  createProgramHeader: {
    gap: spacing.createProgramHeaderToCard,
    alignItems: "stretch",
  },
  createProgramCardSection: {
    gap: spacing.createProgramCardToNext,
    alignItems: "stretch",
  },
  createProgramNextWrap: {
    marginHorizontal: spacing.createProgramCardInset,
  },
  customExerciseAddWrap: {
    marginTop: "auto",
    marginHorizontal: spacing.createProgramCardInset,
  },
  createDayHeader: {
    alignSelf: "stretch",
    minHeight: sizes.backArrowRowMinHeight,
    justifyContent: "center",
  },
  createDayHeaderBack: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    zIndex: 1,
    justifyContent: "center",
  },
  createDayHeaderMenu: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 1,
    justifyContent: "center",
    paddingRight: spacing.createDayBurgerRight,
  },
  createDayHeaderMenuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.saveToBurger,
  },
  createDayBurgerIcon: {
    width: sizes.createDayBurgerWidth,
    height: sizes.createDayBurgerHeight,
  },
  saveIcon: {
    width: sizes.saveIconWidth,
    height: sizes.saveIconHeight,
  },
  clockIcon: {
    width: sizes.programDayExerciseTimerIcon,
    height: sizes.programDayExerciseTimerIcon,
  },
  stopwatchIcon: {
    width: sizes.programDayExerciseTimerIcon,
    height: sizes.programDayExerciseTimerIcon,
  },
  createDayHeaderTitle: {
    ...typography.authTitle,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    paddingHorizontal:
      sizes.backArrowRowMarginLeft +
      sizes.backArrowTriangleSlotWidth +
      sizes.createDayBurgerWidth +
      spacing.createDayBurgerRight,
  },
  createDayHeaderTitleWithSave: {
    paddingHorizontal:
      sizes.backArrowRowMarginLeft +
      sizes.backArrowTriangleSlotWidth +
      sizes.createDayBurgerWidth +
      spacing.createDayBurgerRight +
      sizes.saveIconWidth +
      spacing.saveToBurger,
  },
  createDayHeaderBlock: {
    alignSelf: "stretch",
    gap: spacing.createDayHeaderToBar,
  },
  createDayAccentBar: {
    alignSelf: "stretch",
    height: sizes.createDayAccentBarHeight,
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
  },
  workoutAccentBar: {
    alignSelf: "stretch",
    marginTop: spacing.workoutHeaderToBar,
    height: sizes.workoutAccentBarHeight,
    backgroundColor: colors.backArrow,
    flexDirection: "row",
    alignItems: "center",
  },
  workoutAccentBarLabel: {
    ...typography.doExerciseName,
    color: colors.background,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    textTransform: "uppercase",
    textAlign: "left",
  },
  workoutAccentBarTitle: {
    flex: 1,
    paddingLeft: spacing.workoutAccentBarLabelLeft,
    justifyContent: "center",
  },
  workoutAccentBarPlus: {
    justifyContent: "center",
    paddingRight: spacing.createDayBurgerRight,
  },
  workoutSetHeaders: {
    alignSelf: "stretch",
    marginTop: spacing.workoutBarToSetHeaders,
    paddingLeft: spacing.workoutSetHeadersSide,
    paddingRight: spacing.workoutSetHeadersSide,
    flexDirection: "row",
    alignItems: "center",
  },
  workoutSetHeaderLabel: {
    ...typography.workoutMyPrograms,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
  },
  workoutSetHeaderWeightRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.setScreenWeightLabelToChevron,
  },
  workoutSetWLabel: {
    ...typography.doExerciseName,
    color: colors.workoutSetW,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
  },
  workoutSetWeightLabel: {
    ...typography.doExerciseName,
    color: colors.workoutSetW,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
  },
  workoutSetIndexLabel: {
    ...typography.doExerciseName,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
  },
  workoutSetMutedLabel: {
    ...typography.doExerciseName,
    color: colors.workoutLastWorkout,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
  },
  workoutSetHeadersLine: {
    alignSelf: "stretch",
    marginTop: spacing.workoutSetHeadersToLine,
    height: sizes.programDayDividerHeight,
    backgroundColor: colors.backArrow,
  },
  workoutSetRowLine: {
    alignSelf: "stretch",
    height: sizes.programDayDividerHeight,
    backgroundColor: colors.backArrow,
  },
  workoutSetValuesLine: {
    alignSelf: "stretch",
    marginTop: spacing.workoutLineToSetValues,
    height: sizes.programDayDividerHeight,
    backgroundColor: colors.backArrow,
  },
  workoutSetValues: {
    alignSelf: "stretch",
    marginTop: spacing.workoutLineToSetValues,
    paddingLeft: spacing.workoutSetHeadersSide,
    paddingRight: spacing.workoutSetHeadersSide,
    flexDirection: "row",
    alignItems: "center",
  },
  workoutSetRow: {
    alignSelf: "stretch",
    height: sizes.workoutSetRowHeight,
    justifyContent: "center",
  },
  workoutSetRowValues: {
    marginTop: 0,
  },
  workoutSetStatusBar: {
    position: "absolute",
    left: spacing.workoutSetStatusBarLeft,
    top: 0,
    bottom: 0,
    width: sizes.workoutSetStatusBarWidth,
  },
  workoutSetStatusBarW: {
    backgroundColor: colors.workoutSetW,
  },
  workoutSetStatusBarWorking: {
    backgroundColor: colors.backArrow,
  },
  workoutSetStatusBarDone: {
    backgroundColor: colors.workoutSetWorking,
  },
  workoutSetStatusBarDrop: {
    backgroundColor: colors.resetButtonBorder,
  },
  workoutSetStatusBarEmpty: {
    backgroundColor: colors.inputFill,
  },
  workoutDropSetGroup: {
    alignSelf: "stretch",
    position: "relative",
  },
  workoutDropSetRow: {
    height: sizes.workoutSetRowHeight,
    paddingLeft: spacing.workoutSetHeadersSide,
    paddingRight: spacing.workoutSetHeadersSide,
    flexDirection: "row",
    alignItems: "center",
  },
  workoutSetColSet: {
    flex: 1,
    alignItems: "flex-start",
  },
  workoutSetColWeight: {
    flex: 1,
    alignItems: "center",
  },
  workoutSetColReps: {
    flex: 1,
    alignItems: "flex-end",
  },
  workoutSetValueWithExponent: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  workoutSetValueExponent: {
    ...typography.workoutSetValueExponent,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
  },
  workoutSetValueExponentNegative: {
    ...typography.workoutSetValueExponent,
    color: colors.resetButtonBorder,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
  },
  workoutSetValueExponentHidden: {
    ...typography.workoutSetValueExponent,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    opacity: 0,
  },
  workoutLastWorkout: {
    ...typography.workoutBellBadgeText,
    alignSelf: "stretch",
    marginTop: spacing.workoutLastLineToLastWorkout,
    paddingRight: spacing.workoutLastWorkoutRight,
    color: colors.workoutLastWorkout,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "right",
  },
  createDayAccentBarLabel: {
    ...typography.createDayAccentBarLabel,
    color: colors.background,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
  },
  createDayAccentBarDayLabel: {
    ...typography.createDayAccentBarLabel,
    color: colors.background,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    alignSelf: "stretch",
    paddingLeft: spacing.createDayAccentBarLabelLeft,
    textAlign: "left",
  },
  addExerciseDayRecordLabel: {
    ...typography.addExerciseToDayLabel,
    color: colors.backArrow,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
    alignSelf: "stretch",
  },
  addExerciseDayRecordLink: {
    alignSelf: "stretch",
    marginTop: spacing.addExerciseToDayLabelTop,
  },
  addExerciseAddDayBar: {
    alignSelf: "stretch",
    marginTop: spacing.addExerciseAddDayBarTop,
    height: sizes.createDayAccentBarHeight,
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
  },
  addExerciseDayRecords: {
    alignSelf: "stretch",
    marginTop: spacing.createDayHeaderToBar,
    gap: spacing.addExerciseDayRecordTop,
  },
  addExerciseDayRecord: {
    alignSelf: "stretch",
  },
  addExerciseDayExercises: {
    alignSelf: "stretch",
    marginTop: spacing.addExerciseBarToExercises,
    gap: spacing.doExerciseCirclesGap,
  },
  addExerciseSaveWrap: {
    alignSelf: "stretch",
    marginTop: spacing.addExerciseSaveTop,
    marginHorizontal: spacing.createProgramCardInset,
  },
  workoutScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },

  workoutScreenScroll: {
    flex: 1,
  },
  workoutScreenScrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.safeAreaBottomMin,
  },
  workoutScreenHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingRight: spacing.workoutProfileButtonRight,
  },
  workoutHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.workoutBellToProfile,
    overflow: "visible",
  },
  workoutBellIcon: {
    width: sizes.workoutBellWidth,
    height: sizes.workoutBellHeight,
  },
  workoutBellWrap: {
    width: sizes.workoutBellWidth,
    height: sizes.workoutBellHeight,
    overflow: "visible",
  },
  workoutBellBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: sizes.workoutBellBadge,
    height: sizes.workoutBellBadge,
    borderRadius: sizes.workoutBellBadge / 2,
    backgroundColor: colors.resetButtonBorder,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  workoutBellBadgeText: {
    ...typography.workoutBellBadgeText,
    color: colors.white,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    textAlign: "center",
    includeFontPadding: false,
  },
  workoutGreetingBlock: {
    flexShrink: 1,
  },
  workoutGreeting: {
    ...typography.workoutGreeting,
    paddingLeft: spacing.workoutGreetingLeft,
    color: colors.backArrow,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
  },
  workoutUserName: {
    ...typography.workoutUserName,
    paddingLeft: spacing.workoutUserNameLeft,
    color: colors.inputFill,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
  },
  workoutGlassCardsRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    marginTop: spacing.workoutNameToGlassCards,
    paddingHorizontal: spacing.workoutGlassCardsInset,
    gap: spacing.workoutGlassCardsGap,
  },
  workoutGlassCardWideWrap: {
    alignSelf: "stretch",
    marginTop: spacing.workoutGlassCardsToWide,
    paddingHorizontal: spacing.workoutGlassCardsInset,
    gap: spacing.workoutGlassCardsToWide,
  },
  workoutWeekCalendarWrap: {
    alignSelf: "stretch",
    marginTop: spacing.workoutWeekCalendarTop,
  },
  workoutStartTrainingLabel: {
    alignSelf: "stretch",
    marginTop: spacing.workoutStartTrainingTop,
    paddingHorizontal: spacing.workoutGlassCardsInset,
  },
  workoutTrainingProgramsLabel: {
    alignSelf: "stretch",
    marginTop: spacing.workoutTrainingProgramsTop,
    paddingHorizontal: spacing.workoutGlassCardsInset,
  },
  workoutMyPrograms: {
    ...typography.workoutMyPrograms,
    marginTop: spacing.workoutMyProgramsTop,
    paddingLeft: spacing.workoutGlassCardsInset,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  workoutStartTrainingDay: {
    ...typography.workoutMyPrograms,
    marginTop: spacing.workoutSelectedProgramButtonToDay,
    paddingLeft: spacing.workoutGlassCardsInset,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  workoutCreateProgramButton: {
    alignSelf: "stretch",
    marginTop: spacing.workoutMyProgramsToCreateButton,
    paddingHorizontal: spacing.workoutGlassCardsInset,
    gap: spacing.workoutMyProgramsToCreateButton,
  },
  workoutSelectedProgramButtonWrap: {
    alignSelf: "stretch",
    marginTop: spacing.workoutSelectedProgramToButton,
    paddingRight: spacing.workoutGlassCardsInset,
  },
  workoutProgramFilledButton: {
    backgroundColor: colors.backArrow,
    borderColor: colors.backArrow,
    paddingLeft: spacing.workoutProgramExternalLinkIconLeft,
    paddingRight: spacing.workoutProgramStartIconRight,
  },
  workoutProgramOutlinedButton: {
    paddingLeft: spacing.workoutProgramExternalLinkIconLeft,
    paddingRight: spacing.workoutProgramStartIconRight,
    borderWidth: sizes.workoutProgramThinBorderWidth,
  },
  workoutSelectedProgramButton: {
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderWidth: sizes.workoutProgramThinBorderWidth,
    borderLeftWidth: 0,
    paddingLeft: spacing.workoutSelectedProgramButtonTextLeft,
    alignItems: "flex-start",
  },
  workoutSelectedProgramButtonSelected: {
    backgroundColor: colors.backArrow,
    borderColor: colors.backArrow,
    borderLeftWidth: 0,
  },
  workoutSelectedProgramButtonTextSelected: {
    color: colors.inputText,
  },
  workoutStartTrainingGreenBar: {
    alignSelf: "stretch",
    marginTop: spacing.workoutSelectedProgramButtonToGreenBar,
    height: sizes.workoutStartTrainingBarHeight,
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
  },
  workoutStartTrainingGreenBarText: {
    ...typography.workoutStartTrainingGreenBarText,
    color: colors.inputText,
    fontFamily: fonts.poppinsMedium,
    fontWeight: "500",
    includeFontPadding: false,
  },
  startWorkoutScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  historyScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  historyButtons: {
    alignSelf: "stretch",
    marginTop: spacing.progressHeaderToContent,
    paddingHorizontal: spacing.workoutGlassCardsInset,
    gap: spacing.workoutMyProgramsToCreateButton,
  },
  historyButton: {
    paddingLeft: spacing.historyButtonTextLeft - spacing.workoutGlassCardsInset,
    paddingRight: spacing.historyButtonTextRight - spacing.workoutGlassCardsInset,
    borderWidth: sizes.workoutProgramThinBorderWidth,
    alignItems: "center",
  },
  historyButtonText: {
    ...typography.startWorkoutProgramButtonSubtitle,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
  },
  programDayScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  programDayExerciseScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  programDayExerciseCirclesRow: {
    flexDirection: "column",
    alignSelf: "stretch",
    marginTop: spacing.programDayExerciseHeaderToCircle,
    paddingLeft: spacing.doExerciseCirclesLeft,
    gap: spacing.doExerciseCirclesGap,
  },
  programDayExerciseSelectDayWrap: {
    alignSelf: "stretch",
    marginTop: spacing.workoutLastWorkoutToAddSet,
    paddingHorizontal: spacing.programDayExerciseSelectDaySide,
  },
  setScreenFooter: {
    marginTop: spacing.setScreenFeelingToRecord,
    alignSelf: "stretch",
  },
  setScreenWeightLabelRow: {
    alignSelf: "stretch",
    marginTop: spacing.setScreenHeaderToWeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.setScreenWeightLabelToChevron,
  },
  setScreenWeightLabel: {
    ...typography.doExerciseName,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
    textTransform: "uppercase",
  },
  setScreenChevronIcon: {
    width: sizes.setScreenChevronWidth,
    height: sizes.setScreenChevronHeight,
  },
  setScreenPlusIcon: {
    width: sizes.setScreenPlusIcon,
    height: sizes.setScreenPlusIcon,
  },
  setScreenWeightValue: {
    ...typography.workoutGlassCardValue,
    marginTop: spacing.setScreenWeightLabelToValue,
    color: colors.inputFill,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
    alignSelf: "stretch",
  },
  setScreenWeightValueInput: {
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  setScreenRepsLabel: {
    marginTop: spacing.setScreenLineToFeeling,
    alignSelf: "stretch",
  },
  setScreenWeightLine: {
    alignSelf: "stretch",
    marginTop: spacing.setScreenWeightValueToLine,
    height: sizes.programDayDividerHeight,
    backgroundColor: colors.backArrow,
  },
  setScreenFeelingLabel: {
    ...typography.workoutGlassCardLabel,
    marginTop: spacing.setScreenLineToFeeling,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
    alignSelf: "stretch",
    textTransform: "uppercase",
  },
  setScreenFeelingBar: {
    alignSelf: "stretch",
    marginTop: spacing.setScreenFeelingLabelToBar,
    height: sizes.createDayAccentBarHeight,
    borderTopWidth: sizes.setScreenFeelingBarBorder,
    borderBottomWidth: sizes.setScreenFeelingBarBorder,
    borderColor: colors.backArrow,
    flexDirection: "row",
    alignItems: "stretch",
    overflow: "hidden",
  },
  setScreenFeelingOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  setScreenFeelingOptionLabel: {
    ...typography.workoutGlassCardLabel,
    color: colors.backArrow,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  setScreenFeelingOptionLabelW: {
    color: colors.workoutSetW,
  },
  setScreenFeelingOptionLabelSelected: {
    color: colors.background,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
  },
  setScreenRecordWrap: {
    alignSelf: "stretch",
    paddingHorizontal: spacing.programDayExerciseSelectDaySide,
  },
  setScreenDropSetLink: {
    alignSelf: "stretch",
    marginTop: spacing.setScreenRecordToDropSet,
    alignItems: "center",
  },
  setScreenDropSetLabel: {
    ...typography.addExerciseToDayLabel,
    color: colors.skipLink,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
  },
  dropSetIndexBar: {
    alignSelf: "stretch",
    height: sizes.createDayAccentBarHeight,
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
  },
  dropSetIndexBarFirst: {
    marginTop: spacing.createDayHeaderToBar,
  },
  dropSetWeightLabelRow: {
    alignSelf: "stretch",
    marginTop: spacing.dropSetBarToWeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.setScreenWeightLabelToChevron,
  },
  dropSetAddDropLink: {
    alignSelf: "stretch",
    marginTop: spacing.dropSetLineToAddDrop,
    alignItems: "center",
  },
  dropSetFeelingLabel: {
    ...typography.workoutGlassCardLabel,
    marginTop: spacing.dropSetAddDropToFeeling,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
    alignSelf: "stretch",
    textTransform: "uppercase",
  },
  dropSetFooter: {
    marginTop: spacing.dropSetFeelingToRecord,
    alignSelf: "stretch",
  },
  saveExerciseOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 20,
  },
  saveExerciseOverlayBlur: {
    flex: 1,
  },
  saveExerciseOverlayTint: {
    ...StyleSheet.absoluteFill,
    backgroundColor: colors.saveExerciseOverlay,
  },
  saveExerciseOverlayContent: {
    flex: 1,
    alignItems: "center",
    paddingTop: spacing.saveExerciseOverlayTop,
  },
  saveExerciseFinishWrap: {
    alignSelf: "stretch",
    paddingHorizontal: spacing.programDayExerciseSelectDaySide,
  },
  saveExerciseCancel: {
    marginTop: spacing.saveExerciseButtonToCancel,
    alignItems: "center",
  },
  saveExerciseCancelLabel: {
    ...typography.authLink,
    color: colors.backArrow,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
    fontStyle: "normal",
    includeFontPadding: false,
    textAlign: "center",
  },
  setScreenTimers: {
    marginTop: "auto",
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
  },
  programDayExerciseNamePressable: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  programDayExerciseName: {
    ...typography.doExerciseName,
    flexShrink: 1,
    color: colors.white,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  programDayExerciseTimers: {
    marginTop: spacing.programDayExerciseAddToTimers,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
  },
  workoutTimers: {
    marginTop: spacing.workoutAddSetToTimers,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
  },
  programDayExerciseTimer: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.programDayExerciseTimerIconToText,
  },
  programDayExerciseClockTimer: {
    marginLeft: spacing.programDayExerciseClockLeft,
  },
  programDayExerciseStopwatchTimer: {
    marginLeft: "auto",
    marginRight: spacing.programDayExerciseStopwatchRight,
  },
  programDayExerciseTimerText: {
    ...typography.programDayExerciseTimerText,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    fontStyle: "normal",
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
  },
  programDayExerciseStopwatchTimerText: {
    ...typography.programDayExerciseTimerText,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    fontStyle: "normal",
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
  },
  programDayProgramName: {
    ...typography.workoutMyPrograms,
    marginTop: spacing.programDayHeaderToProgramName,
    paddingLeft: spacing.programDayProgramNameLeft,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  programDayDivider: {
    alignSelf: "stretch",
    marginTop: spacing.programDayProgramNameToLine,
    height: sizes.programDayDividerHeight,
    backgroundColor: colors.backArrow,
  },
  programDayDayLabel: {
    ...typography.startWorkoutProgramButtonText,
    marginTop: spacing.programDayLineToDay,
    paddingLeft: spacing.programDayDayLabelLeft,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  programDayBackButton: {
    marginLeft: spacing.programDayBackLeft,
  },
  programDayEditWrap: {
    alignSelf: "stretch",
    marginTop: spacing.programDayEditTop,
    paddingHorizontal: spacing.programDayExerciseSelectDaySide,
  },
  startWorkoutYourPrograms: {
    ...typography.workoutMyPrograms,
    marginTop: spacing.startWorkoutHeaderToYourPrograms,
    paddingLeft: spacing.workoutGlassCardsInset,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  startWorkoutPresetWorkouts: {
    ...typography.workoutMyPrograms,
    marginTop: spacing.startWorkoutYourProgramsToPreset,
    paddingLeft: spacing.workoutGlassCardsInset,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  startWorkoutProgramButtonText: {
    ...typography.startWorkoutProgramButtonText,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  startWorkoutProgramButtonSubtitle: {
    ...typography.startWorkoutProgramButtonSubtitle,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  startWorkoutProgramButtonSubtitleMeta: {
    ...typography.startWorkoutProgramButtonSubtitle,
    color: colors.white,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  startWorkoutProgramButton: {
    paddingLeft: spacing.startWorkoutProgramButtonLinkLeft,
    paddingRight: spacing.startWorkoutProgramButtonStartRight,
    borderWidth: sizes.workoutProgramThinBorderWidth,
  },
  workoutCreateProgramThinBorder: {
    borderWidth: sizes.workoutProgramThinBorderWidth,
  },
  workoutProgramFilledButtonText: {
    ...typography.workoutProgramFilledButtonText,
    flex: 1,
    color: colors.inputText,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
  },
  workoutProgramOutlinedButtonText: {
    ...typography.workoutProgramFilledButtonText,
    color: colors.inputFill,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
  },
  workoutProgramOutlinedButtonSubtitle: {
    ...typography.workoutMyPrograms,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  workoutProgramOutlinedButtonSubtitleMeta: {
    ...typography.workoutMyPrograms,
    color: colors.backArrow,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  workoutStartIcon: {
    width: sizes.workoutStartIconWidth,
    height: sizes.workoutStartIconHeight,
    flexShrink: 0,
  },
  workoutExternalLinkIcon: {
    width: sizes.workoutExternalLinkIcon,
    height: sizes.workoutExternalLinkIcon,
    flexShrink: 0,
  },
  appButtonWithIcon: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.workoutProgramIconToText,
  },
  appButtonTitleWithIcons: {
    flex: 1,
  },
  appButtonLabelTitle: {
    flexGrow: 0,
    flexShrink: 1,
  },
  appButtonLabelStack: {
    flex: 1,
    justifyContent: "center",
    gap: spacing.startWorkoutProgramButtonTitleToSubtitle,
  },
  appButtonSubtitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.workoutProgramSubtitleMetaGap,
  },
  workoutGlassCard: {
    flex: 1,
    height: sizes.workoutGlassCardHeight,
    borderRadius: sizes.workoutGlassCardRadius,
    backgroundColor: colors.workoutGlassCardFill,
    alignItems: "center",
    justifyContent: "center",
  },
  workoutGlassCardWide: {
    alignSelf: "stretch",
    height: sizes.workoutGlassCardWideHeight,
    borderRadius: sizes.workoutGlassCardRadius,
    backgroundColor: colors.workoutGlassCardFill,
  },
  workoutGlassCardBlurClip: {
    overflow: "hidden",
  },
  workoutGlassCardContent: {
    alignItems: "center",
    gap: spacing.workoutGlassCardValueToLabel,
  },
  workoutGlassCardValue: {
    ...typography.workoutGlassCardValue,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    textAlign: "center",
    includeFontPadding: false,
  },
  workoutGlassCardLabel: {
    ...typography.workoutGlassCardLabel,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    textAlign: "center",
    includeFontPadding: false,
  },
  workoutProfileButton: {
    width: sizes.workoutProfileButton,
    height: sizes.workoutProfileButton,
    borderRadius: sizes.workoutProfileButton / 2,
    backgroundColor: colors.backArrow,
  },
  menuOverlayRoot: {
    ...StyleSheet.absoluteFill,
    zIndex: 20,
    overflow: "visible",
  },
  menuOverlayDismissArea: {
    flex: 1,
  },
  menuOverlayPanel: {
    height: sizes.menuOverlayPanelHeight,
    paddingTop: spacing.menuOverlayHeaderTop,
    paddingHorizontal: spacing.menuOverlayHeaderHorizontal,
    backgroundColor: colors.background,
    ...shadows.profileFieldSheet,
  },
  menuOverlayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  menuOverlayTitle: {
    ...typography.menuOverlayTitle,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
  },
  menuOverlayProLink: {
    ...typography.menuOverlayProLink,
    color: colors.menuOverlayProLink,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "right",
  },
  menuGridItem: {
    position: "absolute",
    alignItems: "center",
    width: sizes.menuGridItemWidth,
    gap: spacing.menuIconToLabel,
  },
  menuGridIconWrap: {
    width: sizes.menuIconSize,
    height: sizes.menuIconSize,
    alignItems: "center",
    justifyContent: "center",
  },
  menuGridLabel: {
    ...typography.menuGridLabel,
    color: colors.backArrow,
    fontFamily: fonts.poppinsLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  progressScreenScroll: {
    flex: 1,
  },
  progressScreenScrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.progressScreenBottom,
    paddingTop: spacing.progressHeaderToContent,
    gap: spacing.progressSectionGap,
  },
  progressSection: {
    alignSelf: "stretch",
    gap: spacing.progressSectionLabelToRows,
  },
  progressSectionLabel: {
    ...typography.progressSectionLabel,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    paddingLeft: spacing.profileActionButtonInset,
  },
  progressRowList: {
    alignSelf: "stretch",
    gap: spacing.profileActionButtonGap,
  },
  progressRowButton: {
    alignSelf: "stretch",
    height: sizes.profileActionButtonHeight,
    marginHorizontal: spacing.profileActionButtonInset,
    borderRadius: sizes.authInputRadius,
    backgroundColor: colors.inputFill,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.profileActionButtonTextLeft,
    paddingRight: spacing.profileActionButtonTextLeft,
    gap: spacing.profileActionButtonTextLeft,
  },
  progressMuscleScroll: {
    flex: 1,
  },
  progressMuscleScrollContent: {
    flexGrow: 1,
    paddingTop: spacing.progressHeaderToContent,
    paddingBottom: spacing.progressMuscleScrollBottom,
  },
  progressMuscleExerciseList: {
    flexDirection: "column",
    alignSelf: "stretch",
    paddingLeft: spacing.doExerciseCirclesLeft,
    gap: spacing.doExerciseCirclesGap,
  },
  progressMetricScroll: {
    flex: 1,
  },
  progressMetricScrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.progressScreenBottom,
  },
  progressMetricDiagramWrap: {
    alignSelf: "stretch",
    marginTop: spacing.progressMetricDiagramTop,
    paddingHorizontal: spacing.progressMetricDiagramInset,
  },
  progressMetricDiagram: {
    alignSelf: "stretch",
    height: sizes.progressMetricDiagramHeight,
    borderRadius: sizes.workoutGlassCardRadius,
    backgroundColor: colors.workoutGlassCardFill,
    alignItems: "center",
    justifyContent: "center",
  },
  progressMetricDiagramLabel: {
    ...typography.progressMetricDiagramLabel,
    color: colors.textMuted,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
    textTransform: "lowercase",
  },
  progressMetricHistoryBlock: {
    alignSelf: "stretch",
    marginTop: spacing.progressMetricHistoryTop,
  },
  progressMetricHistoryDivider: {
    alignSelf: "stretch",
    height: 1,
    backgroundColor: colors.divider,
  },
  progressMetricHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 49,
    paddingHorizontal: spacing.progressMetricDiagramInset,
  },
  progressMetricHistoryDate: {
    ...typography.progressMetricHistoryDate,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  progressMetricHistoryValue: {
    ...typography.progressMetricHistoryValue,
    color: colors.inputFill,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  progressMetricRecordButton: {
    alignSelf: "center",
    marginTop: spacing.progressMetricRecordTop,
    paddingVertical: spacing.progressSectionLabelToRows,
    paddingHorizontal: spacing.progressHeaderToContent,
  },
  progressMetricRecordButtonText: {
    ...typography.progressMetricRecordButtonText,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
  },
  progressMetricHistoryValueWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.progressSectionLabelToRows,
  },
  progressMetricDetailScrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.progressScreenBottom,
  },
  profileAvatar: {
    width: sizes.profileAvatar,
    height: sizes.profileAvatar,
    minWidth: sizes.profileAvatar,
    minHeight: sizes.profileAvatar,
    borderRadius: sizes.profileAvatar / 2,
    backgroundColor: colors.white,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  profileAvatarImage: {
    width: sizes.profileAvatar,
    height: sizes.profileAvatar,
  },
  profileAvatarCamera: {
    width: sizes.profileAvatarCameraWidth,
    height: sizes.profileAvatarCameraHeight,
  },
  profileAvatarBlock: {
    alignItems: "center",
    gap: spacing.profileAvatarToUploadLabel,
  },
  profileUploadPhotoText: {
    ...typography.profileUploadPhoto,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    textAlign: "center",
  },
  profileUploadHintText: {
    ...typography.profileUploadPhoto,
    color: colors.inputFill,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    textAlign: "center",
  },
  profileUploadLabels: {
    alignItems: "center",
  },
  profileActionButton: {
    alignSelf: "stretch",
    height: sizes.profileActionButtonHeight,
    marginHorizontal:
      spacing.profileActionButtonInset - layout.screenPaddingHorizontal,
    borderRadius: sizes.authInputRadius,
    backgroundColor: colors.inputFill,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.profileActionButtonTextLeft,
    paddingRight: spacing.profileActionButtonTextLeft,
    gap: spacing.profileActionButtonTextLeft,
  },
  profileActionButtonText: {
    ...typography.authLabel,
    flex: 1,
    color: colors.inputText,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "left",
  },
  profileActionButtonChevron: {
    width: sizes.profileActionButtonChevronWidth,
    height: sizes.profileActionButtonChevronHeight,
    flexShrink: 0,
  },
  profileActionButtons: {
    alignSelf: "stretch",
    gap: spacing.profileActionButtonGap,
  },
  profileActionSection: {
    alignSelf: "stretch",
  },
  profileConnectorsText: {
    ...typography.profileConnectors,
    marginTop: spacing.profileButtonsToConnectors,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    textAlign: "center",
    alignSelf: "stretch",
  },
  profileConnectorItems: {
    alignSelf: "stretch",
    marginTop: spacing.profileConnectorsToItems,
    marginHorizontal:
      spacing.profileActionButtonInset - layout.screenPaddingHorizontal,
    gap: spacing.profileConnectorItemGap,
  },
  profileConnectorRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.profileConnectorItemGap,
  },
  profileConnectorItemText: {
    ...typography.profileConnectorItem,
    flexShrink: 1,
    color: colors.inputFill,
    fontFamily: fonts.poppinsLight,
    fontWeight: "300",
    textAlign: "left",
  },
  profileConnectorStatusText: {
    ...typography.profileConnectorItem,
    flex: 1,
    fontFamily: fonts.poppinsLight,
    fontWeight: "300",
    textAlign: "center",
  },
  profileConnectorStatusConnected: {
    color: colors.backArrow,
  },
  profileConnectorStatusDisconnected: {
    color: colors.resetButtonBorder,
  },
  profileConnectorGarminStatusText: {
    transform: [{ translateX: -spacing.profileConnectorGarminStatusNudge }],
  },
  profileLogOutText: {
    ...typography.profileLogOut,
    marginTop: spacing.profileConnectorsToLogOut,
    color: colors.backArrow,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
    textAlign: "center",
    alignSelf: "stretch",
  },
  profileDeleteAccountText: {
    ...typography.profileDeleteAccount,
    marginTop: spacing.profileLogOutToDeleteAccount,
    color: colors.profileDeleteAccount,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
    textAlign: "center",
    alignSelf: "stretch",
  },
  profileFieldSheetRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  profileFieldSheetBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: colors.surface,
  },
  profileFieldSheetPanel: {
    alignSelf: "stretch",
    height: sizes.profileFieldSheetHeight,
    borderRadius: 0,
    backgroundColor: colors.background,
    paddingHorizontal: layout.screenPaddingHorizontal,
    paddingTop: spacing.profileFieldSheetTop,
    gap: spacing.profileFieldSheetCardToButton,
    ...shadows.profileFieldSheet,
  },
  profileBirthdaySheetPanel: {
    alignSelf: "stretch",
    borderRadius: 0,
    backgroundColor: colors.background,
    paddingHorizontal: layout.screenPaddingHorizontal,
    paddingTop: spacing.profileFieldSheetTop,
    paddingBottom: spacing.profileBirthdaySheetBottom,
    gap: spacing.profileFieldSheetCardToButton,
    ...shadows.profileFieldSheet,
  },
  profileBirthdayCalendar: {
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
  },
  profileBirthdayCalendarPicker: {
    alignSelf: "center",
  },
  profileWeekDaySheetPanel: {
    alignSelf: "stretch",
    borderRadius: 0,
    backgroundColor: colors.background,
    paddingHorizontal: layout.screenPaddingHorizontal,
    paddingTop: spacing.profileFieldSheetTop,
    paddingBottom: spacing.profileBirthdaySheetBottom,
    gap: spacing.profileFieldSheetCardToButton,
    ...shadows.profileFieldSheet,
  },
  profileWeekDayPicker: {
    alignSelf: "stretch",
  },
  profileWeekDayPickerItem: {
    color: colors.backArrow,
  },
  profileAvatarInner: {
    position: "absolute",
    width: sizes.profileAvatarInner,
    height: sizes.profileAvatarInner,
    minWidth: sizes.profileAvatarInner,
    minHeight: sizes.profileAvatarInner,
    borderRadius: sizes.profileAvatarInner / 2,
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
    zIndex: 1,
  },
  profileAvatarPlus: {
    width: sizes.profileAvatarPlus,
    height: sizes.profileAvatarPlus,
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarPlusBarHorizontal: {
    position: "absolute",
    width: sizes.profileAvatarPlus,
    height: sizes.profileAvatarPlusStroke,
    backgroundColor: colors.background,
  },
  profileAvatarPlusBarVertical: {
    position: "absolute",
    width: sizes.profileAvatarPlusStroke,
    height: sizes.profileAvatarPlus,
    backgroundColor: colors.background,
  },
  profileScreenBackButton: {
    position: "absolute",
    left: 0,
    zIndex: 1,
  },
  profileScreenScroll: {
    flex: 1,
  },
  profileScreenContent: {
    paddingHorizontal: layout.screenPaddingHorizontal,
  },
  profileScreenScrollContent: {
    flexGrow: 1,
  },
  profileScreenBody: {
    width: "100%",
    maxWidth: layout.authMaxWidth,
    alignSelf: "center",
    gap: spacing.profileUploadToButtons,
  },
  backArrowRow: {
    minHeight: sizes.backArrowRowMinHeight,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: sizes.backArrowRowMarginLeft,
  },
  backArrowTriangleSlot: {
    width: sizes.backArrowTriangleSlotWidth,
    height: sizes.backArrowTriangleSlotHeight,
    alignItems: "center",
    justifyContent: "center",
  },
  backArrowTriangle: {
    width: 0,
    height: 0,
    borderTopWidth: sizes.backArrowTriangleBorder,
    borderBottomWidth: sizes.backArrowTriangleBorder,
    borderRightWidth: sizes.backArrowTriangleWidth,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderRightColor: colors.backArrow,
  },
  authScreenTitle: {
    ...typography.authTitle,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    flexShrink: 0,
  },
  authScreenTitleTextCenter: {
    textAlign: "center",
  },
  signInScreen: {
    ...authScreenBase,
    gap: spacing.signInForm,
  },
  signInHeader: {
    gap: spacing.signInHeader,
    alignItems: "center",
  },
  signUpScreen: {
    ...authScreenBase,
    gap: spacing.signUpLegal,
  },
  signUpPostHeader: {
    flex: 1,
    gap: spacing.signUpPostHeader,
    alignSelf: "stretch",
  },
  signUpHeader: {
    gap: spacing.signUpHeader,
    alignItems: "stretch",
  },
  forgotPasswordHeader: {
    gap: spacing.forgotPasswordHeader,
    alignItems: "stretch",
  },
  newPasswordHeader: {
    gap: spacing.newPasswordHeader,
    alignItems: "stretch",
  },
  forgotPasswordScreen: {
    ...authScreenBase,
    gap: spacing.forgotPasswordForm,
  },
  forgotPasswordFormContent: {
    ...authBleedStretch,
  },
  verifyEmailScreen: {
    ...authScreenBase,
    gap: spacing.verifyEmailForm,
  },
  verifyEmailHeader: {
    gap: spacing.verifyEmailHeader,
    alignItems: "stretch",
  },
  verifyEmailFormContent: {
    ...authBleedStretch,
    gap: spacing.formGap,
  },
  verifyEmailCard: {
    paddingVertical: 28,
    paddingHorizontal: 24,
    gap: spacing.fieldStack,
  },
  verifyEmailMessage: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  verifyEmailAddress: {
    color: colors.legalLink,
    fontFamily: fonts.leagueSpartanBold,
    fontWeight: "700",
  },
  verifyEmailHint: {
    ...typography.authSmall,
    color: colors.textMuted,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  newPasswordScreen: {
    ...authScreenBase,
    gap: spacing.newPasswordForm,
  },
  newPasswordFormContent: {
    ...authBleedStretch,
  },
  genderScreen: {
    ...authScreenBase,
  },
  genderHeader: {
    alignItems: "stretch",
  },
  genderHeaderToOptionsGap: {
    height: spacing.genderHeaderToButtons,
    alignSelf: "stretch",
  },
  genderOptions: {
    flexDirection: "row",
    alignSelf: "stretch",
    alignItems: "stretch",
    gap: spacing.genderOptions,
    paddingHorizontal: spacing.genderOptionsScreenInset,
    marginHorizontal: -layout.screenPaddingHorizontal,
  },
  genderOption: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: sizes.genderOptionMaleButtonWidth,
    alignItems: "stretch",
  },
  genderOptionButton: {
    height: sizes.genderOptionButtonHeight,
    width: "100%",
    alignSelf: "stretch",
  },
  genderOptionButtonText: {
    ...typography.authButtonText,
    color: colors.inputFill,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
  },
  genderOptionButtonTextSelected: {
    color: colors.inputText,
  },
  genderOptionMaleSelected: {
    backgroundColor: colors.genderMale,
    borderColor: colors.genderMale,
  },
  genderOptionFemaleSelected: {
    backgroundColor: colors.genderFemale,
    borderColor: colors.genderFemale,
  },
  weightScreen: {
    ...authScreenBase,
  },
  weightHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  weightHeaderToToggleGap: {
    height: spacing.weightHeader,
    alignSelf: "stretch",
  },
  weightUnitToggleWrap: {
    flexShrink: 0,
    marginHorizontal: spacing.weightUnitToggleScreenInset - layout.screenPaddingHorizontal,
  },
  weightUnitToggle: {
    position: "relative",
    flexDirection: "row",
    alignSelf: "stretch",
    height: sizes.weightUnitToggleHeight,
    borderRadius: sizes.authButtonRadius,
    overflow: "hidden",
    backgroundColor: colors.white,
  },
  weightUnitToggleThumb: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: sizes.authButtonRadius,
  },
  weightUnitToggleSegments: {
    flex: 1,
    flexDirection: "row",
    zIndex: 1,
  },
  weightUnitToggleSegment: {
    flex: 1,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  weightUnitToggleLabel: {
    ...typography.authTitle,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.inputPlaceholder,
    includeFontPadding: false,
  },
  weightRulerPicker: {
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "visible",
  },
  weightRulerPickerBody: {
    marginTop: spacing.weightToggleToRuler,
    marginHorizontal: -layout.screenPaddingHorizontal,
    overflow: "visible",
  },
  weightRulerPickerViewport: {
    height:
      sizes.weightRulerNumberRowHeight +
      spacing.weightRulerNumberToBar +
      sizes.weightRulerBarHeight,
    overflow: "visible",
  },
  weightRulerStepColumn: {
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  weightRulerBarSegment: {
    width: "100%",
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
  },
  weightRulerTickMinor: {
    backgroundColor: colors.white,
    opacity: 0.45,
  },
  weightRulerTickHalf: {
    backgroundColor: colors.white,
  },
  weightRulerTickMajor: {
    backgroundColor: colors.white,
  },
  weightRulerNumberLabel: {
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    overflow: "visible",
  },
  weightRulerNumberLabelSlot: {
    position: "absolute",
    top: 0,
    height: sizes.weightRulerNumberRowHeight,
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  weightRulerNeedle: {
    position: "absolute",
    top:
      sizes.weightRulerNumberRowHeight +
      spacing.weightRulerNumberToBar +
      (sizes.weightRulerBarHeight - sizes.weightRulerNeedleHeight) / 2,
    left: "50%",
    width: sizes.weightRulerNeedleWidth,
    height: sizes.weightRulerNeedleHeight,
    marginLeft: -sizes.weightRulerNeedleWidth / 2,
    backgroundColor: colors.black,
    zIndex: 2,
  },
  weightRulerReadout: {
    alignItems: "center",
    marginTop: spacing.weightRulerToReadout,
    gap: spacing.weightRulerReadoutArrowToValue,
    overflow: "visible",
  },
  authReadoutArrow: {
    width: sizes.authReadoutArrowWidth,
    height: sizes.authReadoutArrowHeight,
    alignSelf: "center",
    transform: [{ scale: sizes.authReadoutArrowScale }],
  },
  weightRulerReadoutRow: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "flex-start",
    paddingLeft: spacing.weightRulerReadoutValueLeftGap,
    gap: spacing.weightRulerReadoutUnitGap,
    overflow: "visible",
  },
  weightRulerReadoutValue: {
    ...typography.weightRulerReadoutValue,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    flexShrink: 0,
    overflow: "visible",
  },
  weightRulerReadoutUnit: {
    ...typography.weightRulerReadoutUnit,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    marginBottom: sizes.weightRulerReadoutUnitOffset,
  },
  authFormFooter: {
    alignSelf: "stretch",
    gap: spacing.authSkipToNext,
  },
  authFormFooterButtonRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    alignItems: "stretch",
    paddingHorizontal: spacing.genderOptionsScreenInset,
    marginHorizontal: -layout.screenPaddingHorizontal,
  },
  authFormFooterNextButton: {
    flex: 1,
    height: sizes.authButtonHeight,
    alignSelf: "stretch",
  },
  authFormFooterButtonRowHidden: {
    opacity: 0,
  },
  ageScreen: {
    ...authScreenBase,
  },
  ageHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  ageHeaderToSelectionGap: {
    height: spacing.ageHeaderToSelection,
    alignSelf: "stretch",
  },
  ageWheelPicker: {
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "visible",
  },
  ageWheelReadout: {
    alignItems: "center",
    overflow: "visible",
  },
  ageWheelReadoutBridge: {
    height: spacing.ageReadoutToWheel,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: spacing.ageWheelRulerToArrow,
    overflow: "visible",
  },
  ageWheelReadoutValue: {
    ...typography.ageWheelReadoutValue,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    overflow: "visible",
  },
  ageWheelBanner: {
    marginHorizontal: -layout.screenPaddingHorizontal,
    height: sizes.ageWheelBannerHeight,
    alignSelf: "stretch",
    backgroundColor: colors.backArrow,
    overflow: "hidden",
    position: "relative",
    zIndex: 1,
  },
  ageWheelSegmentSlot: {
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  ageWheelSegmentContent: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  ageWheelSelectionFrame: {
    position: "absolute",
    top: 0,
    borderRadius: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: sizes.ageWheelSelectedBorderWidth,
    borderRightWidth: sizes.ageWheelSelectedBorderWidth,
    borderColor: colors.inputText,
    pointerEvents: "none",
  },
  ageWheelSegmentLabel: {
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    paddingTop: sizes.ageWheelSelectedLabelNudge,
    overflow: "visible",
  },
  heightScreen: {
    ...authScreenBase,
  },
  heightHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  heightRulerPicker: {
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "visible",
  },
  heightRulerReadout: {
    alignItems: "center",
    marginTop: spacing.heightHeaderToReadout,
    overflow: "visible",
  },
  heightRulerReadoutRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: spacing.weightRulerReadoutUnitGap,
    overflow: "visible",
  },
  heightRulerReadoutValue: {
    ...typography.heightRulerReadoutValue,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    flexShrink: 0,
    overflow: "visible",
  },
  heightRulerReadoutUnit: {
    ...typography.weightRulerReadoutUnit,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    marginBottom: sizes.heightRulerReadoutUnitOffset,
  },
  heightRulerPickerBody: {
    marginTop: spacing.heightReadoutToRuler,
    alignItems: "center",
    overflow: "visible",
  },
  heightRulerPickerFrame: {
    position: "relative",
    overflow: "visible",
  },
  heightRulerPickerViewport: {
    overflow: "hidden",
  },
  heightRulerBarTrack: {
    position: "absolute",
    top: 0,
    right: 0,
    width: sizes.heightRulerBarWidth,
    height: sizes.heightRulerViewportHeight,
    borderRadius: sizes.heightRulerBarRadius,
    backgroundColor: colors.backArrow,
    overflow: "hidden",
  },
  heightRulerList: {
    flex: 1,
  },
  heightRulerStepRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  heightRulerBarSegment: {
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  heightRulerTickMinor: {
    width: sizes.heightRulerTickMinorWidth,
    height: sizes.heightRulerTickMinorHeight,
    alignSelf: "center",
    backgroundColor: colors.white,
    opacity: 0.45,
  },
  heightRulerTickHalf: {
    width: sizes.heightRulerTickHalfWidth,
    height: sizes.heightRulerTickHalfHeight,
    alignSelf: "center",
    backgroundColor: colors.white,
  },
  heightRulerTickMajor: {
    width: sizes.heightRulerTickMajorWidth,
    height: sizes.heightRulerTickMajorHeight,
    alignSelf: "center",
    backgroundColor: colors.white,
  },
  heightRulerNumberLabel: {
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    overflow: "visible",
  },
  heightRulerNumberLabelSlot: {
    position: "absolute",
    left: 0,
    height: sizes.weightRulerNumberRowHeight,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  heightRulerNeedle: {
    position: "absolute",
    top: "50%",
    right: (sizes.heightRulerBarWidth - sizes.heightRulerNeedleWidth) / 2,
    width: sizes.heightRulerNeedleWidth,
    height: sizes.heightRulerNeedleHeight,
    marginTop: -sizes.heightRulerNeedleHeight / 2,
    backgroundColor: colors.black,
    zIndex: 2,
  },
  heightRulerNeedlePointer: {
    position: "absolute",
    top: "50%",
    left: "100%",
    marginLeft: spacing.heightRulerNeedlePointerGap,
    marginTop: -(sizes.authReadoutArrowWidth * sizes.authReadoutArrowScale) / 2,
    zIndex: 3,
    overflow: "visible",
  },
  heightRulerNeedlePointerArrow: {
    transform: [{ rotate: "-90deg" }],
  },
  sportsExperienceScreen: {
    ...authScreenBase,
  },
  sportsExperienceHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  sportsExperienceHeaderToOptionsGap: {
    height: spacing.sportsExperienceHeaderToOptions,
    alignSelf: "stretch",
  },
  sportsExperienceOptions: {
    alignSelf: "stretch",
    gap: spacing.sportsExperienceOptions,
    paddingHorizontal: spacing.genderOptionsScreenInset,
    marginHorizontal: -layout.screenPaddingHorizontal,
  },
  sportsExperienceOptionButton: {
    alignSelf: "stretch",
    width: "100%",
  },
  sportsExperienceBeginnerButton: {
    backgroundColor: colors.sportsExperienceBeginner,
  },
  sportsExperienceGymRatButton: {
    backgroundColor: colors.sportsExperienceGymRat,
  },
  sportsExperienceBeastModeButton: {
    backgroundColor: colors.sportsExperienceBeastMode,
  },
  sportsExperienceOptionButtonText: {
    ...typography.sportsExperienceOptionButton,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    color: colors.inputText,
    includeFontPadding: false,
  },
  forgotPasswordInputsCard: {
    paddingBottom: sizes.forgotPasswordCardPaddingBottom,
    backgroundColor: colors.successCardTint,
  },
  newPasswordInputsCard: {
    paddingBottom: sizes.newPasswordCardPaddingBottom,
    backgroundColor: colors.successCardTint,
  },
  successBody: {
    ...authBleedStretch,
    gap: spacing.successBody,
  },
  successActions: {
    alignItems: "center",
    gap: spacing.successActions,
  },
  supportResultBody: {
    ...authBleedStretch,
    gap: spacing.supportResultBody,
  },
  supportErrorOk: {
    ...supportOkTextBase,
    color: colors.backArrow,
  },
  supportSubmittedOk: {
    ...supportOkTextBase,
    color: colors.supportOkInactive,
  },
  errorResultCard: {
    backgroundColor: colors.errorCardTint,
  },
  supportSubmittedCard: {
    backgroundColor: colors.supportCardTint,
  },
  successResultCard: {
    backgroundColor: colors.successCardTint,
  },
  authResultCardShadow: {
    alignSelf: "stretch",
    borderRadius: layout.authCardRadius,
    backgroundColor: colors.background,
    ...shadows.authCard,
  },
  authBlurInputsCardWrap: {
    alignSelf: "stretch",
    borderRadius: layout.authCardRadius,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  authInputsCardShadow: {
    marginHorizontal: layout.authCardBleed,
  },
  errorContact: {
    alignItems: "center",
    gap: spacing.errorContact,
  },
  errorFormActions: {
    alignItems: "center",
    gap: spacing.errorFormActions,
  },
  errorOrText: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  contactUsScreen: {
    ...authScreenBase,
    gap: spacing.contactUsForm,
  },
  contactUsHeader: {
    gap: spacing.contactUsHeader,
    alignItems: "stretch",
  },
  contactUsFormContent: {
    ...authBleedStretch,
  },
  contactUsInputsCard: {
    paddingBottom: sizes.contactUsCardPaddingBottom,
    position: "relative",
    overflow: "visible",
    backgroundColor: colors.supportCardTint,
  },
  contactUsCardIconCorner: {
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 1,
  },
  contactUsCardIconCircle: {
    marginRight: 0,
  },
  contactUsTextArea: {
    height: sizes.contactTextAreaHeight,
    paddingTop: sizes.textAreaPaddingVertical,
    paddingBottom: sizes.textAreaPaddingVertical,
    textAlignVertical: "top",
  },
  contactUsHelpTitle: {
    ...typography.authTitle,
    color: colors.supportHeader,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    marginBottom: spacing.contactHelpTitleBottom,
    textAlign: "center",
    includeFontPadding: false,
  },
  contactUsFieldLabel: {
    color: colors.supportHeader,
  },
  successHeader: {
    gap: spacing.successHeader,
    alignItems: "stretch",
  },
  successCard: {
    alignSelf: "stretch",
    height: sizes.authResultCardHeight,
    borderRadius: layout.authCardRadius,
    backgroundColor: colors.cardSurface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: "visible",
    paddingHorizontal: layout.screenPaddingHorizontal,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  successCardText: {
    ...typography.authTitle,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    textAlign: "center",
    includeFontPadding: false,
    flex: 1,
  },
  authResultIconCircleShadow: {
    width: sizes.authResultCardHeight,
    height: sizes.authResultCardHeight,
    marginRight: -layout.screenPaddingHorizontal,
    borderRadius: sizes.authResultCardHeight / 2,
    backgroundColor: colors.background,
    ...shadows.authCard,
  },
  authResultIconCircleWrap: {
    width: sizes.authResultCardHeight,
    height: sizes.authResultCardHeight,
    borderRadius: sizes.authResultCardHeight / 2,
  },
  successCardIconCircle: {
    width: "100%",
    height: "100%",
    borderRadius: sizes.authResultCardHeight / 2,
    backgroundColor: colors.cardSurface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  successCardIconCircleError: {
    backgroundColor: colors.errorCardTint,
  },
  successCardIconCircleSuccess: {
    backgroundColor: colors.successCardTint,
  },
  successCardIconCircleSupport: {
    backgroundColor: colors.supportCardTint,
  },
  successCardIcon: {
    width: sizes.successCardIcon,
    height: sizes.successCardIcon,
  },
  successCardTextError: {
    color: colors.resetButtonBorder,
  },
  successCardTextSupport: {
    color: colors.supportHeader,
  },
  card: {
    width: "100%",
    maxWidth: layout.authMaxWidth,
    alignSelf: "center",
    gap: spacing.cardGap,
    backgroundColor: colors.surface,
  },
  signUpFormContent: {
    flex: 1,
    ...authBleedStretch,
  },
  signUpInputsCard: {
    ...authInputsCardBase,
    backgroundColor: colors.successCardTint,
  },
  signInInputsCard: {
    alignSelf: "stretch" as const,
    borderRadius: layout.authCardRadius,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: "hidden" as const,
    backgroundColor: "transparent",
  },
  signInInputsCardTint: {
    ...StyleSheet.absoluteFill,
    backgroundColor: colors.successCardTint,
  },
  signInInputsCardContent: {
    paddingTop: sizes.authCardPaddingTop,
    paddingLeft: sizes.authCardPaddingLeft,
    paddingRight: sizes.authCardPaddingRight,
    paddingBottom: sizes.authCardPaddingBottom,
  },
  signInFormContent: {
    flex: 1,
    gap: spacing.orSignWith,
    ...authBleedStretch,
  },
  authInputError: {
    borderWidth: 3,
    borderColor: colors.resetButtonBorder,
  },
  authInputFocused: {
    borderWidth: 3,
    borderColor: colors.backArrow,
  },
  signInSocialGroup: {
    alignItems: "center",
    gap: spacing.socialGroup,
  },
  signInForgotLink: {
    marginTop: spacing.forgotPasswordLink,
    alignSelf: "flex-end",
  },
  signInForgotLinkText: {
    ...typography.authLabel,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    includeFontPadding: false,
  },
  signInOrSignWith: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  signUpInputGroup: {
    gap: spacing.fieldStack,
  },
  signUpCardFields: {
    gap: spacing.cardFields,
  },
  signUpSocialGroup: {
    alignItems: "center",
    gap: spacing.socialGroup,
  },
  authFormField: {
    width: "100%",
  },
  authVideoBackground: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 0,
    overflow: "hidden",
  },
  authVideo: {
    width: "100%",
    height: "100%",
  },
  title: {
    ...typography.authTitle,
    fontWeight: "700",
    color: colors.text,
  },
  description: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 2,
    height: 34,
    paddingHorizontal: 12,
    paddingVertical: 0,
    backgroundColor: colors.inputBg,
    color: colors.text,
    fontSize: 16,
    textAlignVertical: "center",
  },
  signUpInput: {
    height: sizes.authInputHeight,
    backgroundColor: colors.inputFill,
    borderColor: colors.inputFill,
    borderRadius: sizes.authInputRadius,
    color: colors.inputText,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    ...typography.authInput,
  },
  signUpInputLabel: {
    ...typography.authLabel,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    marginBottom: 8,
    includeFontPadding: false,
  },
  signUpOrSignWith: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  signUpLegalText: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
    marginHorizontal: layout.authCardBleed,
  },
  signUpLegalLink: {
    color: colors.legalLink,
    fontFamily: fonts.leagueSpartanBold,
    fontWeight: "700",
  },
  signUpGoogleButton: {
    alignSelf: "center",
  },
  signUpGoogleIcon: {
    width: sizes.googleIcon,
    height: sizes.googleIcon,
  },
  appButton: {
    alignSelf: "stretch",
    height: sizes.authButtonHeight,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    borderWidth: 3,
    borderColor: colors.backArrow,
    borderRadius: sizes.authButtonRadius,
    overflow: "hidden",
  },
  appButtonText: {
    ...typography.authButtonText,
    fontFamily: fonts.montserratRegular,
    color: colors.inputFill,
  },
  appButtonDisabled: {
    opacity: 0.55,
  },
  signUpLoginLink: {
    marginTop: "auto",
    alignSelf: "center",
  },
  signUpLoginLinkText: {
    ...typography.authLink,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  authSkipLink: {
    alignSelf: "center",
    paddingTop: spacing.authSkipLinkVertical,
    paddingBottom: spacing.authSkipLinkBottom,
  },
  authSkipLinkText: {
    ...typography.authSkip,
    color: colors.skipLink,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
  },
  authSkipFooter: {
    alignItems: "center",
    marginTop: spacing.authSkipToNext,
    paddingHorizontal: layout.screenPaddingHorizontal,
    flexShrink: 0,
  },
  divider: {
    height: 1,
    backgroundColor: colors.divider,
    marginVertical: 4,
    width: "100%",
    maxWidth: layout.authMaxWidth,
  },
  appleButton: {
    width: "100%",
    height: 44,
  },
  appleButtonDisabled: {
    opacity: 0.5,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: colors.backdrop,
    alignItems: "center",
    justifyContent: "center",
    padding: layout.screenPaddingHorizontal,
  },
  modalCard: {
    width: "100%",
    maxWidth: 320,
    backgroundColor: colors.modalSurface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderMuted,
    paddingHorizontal: 20,
    paddingVertical: layout.screenPaddingHorizontal,
    gap: spacing.tabContent,
    alignItems: "center",
  },
  modalMessage: {
    ...typography.authButtonText,
    fontWeight: "700",
    color: colors.text,
    textAlign: "center",
    lineHeight: 26,
  },
  modalButton: {
    alignSelf: "stretch",
    borderWidth: 1,
    borderColor: colors.white,
    borderRadius: 2,
    paddingVertical: sizes.textAreaPaddingVertical,
    alignItems: "center",
  },
  modalButtonText: {
    color: colors.buttonText,
    fontSize: 16,
    fontWeight: "600",
  },
});
