import { StyleSheet } from "react-native";

export const colors = {
  // hsba(143, 55%, 11%, 1) — dark, top of gradient
  gradientTop: "#0D1C13",
  // hsba(143, 55%, 51%, 1) — lighter green, bottom of gradient
  gradientBottom: "#3B8256",
  inputBg: "rgba(6, 28, 18, 0.55)",
  border: "rgba(255, 255, 255, 0.55)",
  borderMuted: "rgba(255, 255, 255, 0.35)",
  text: "#FFFFFF",
  textMuted: "rgba(255, 255, 255, 0.72)",
  textSecondary: "rgba(255, 255, 255, 0.85)",
  placeholder: "rgba(255, 255, 255, 0.45)",
  accent: "#C6F54B",
  // hsba(83, 56%, 86%, 1) — primary button text fill
  buttonText: "#ACDB60",
  white: "#FFFFFF",
  // hsba(52, 6%, 93%, 1) — primary button border
  buttonBorder: "#EDEBDF",
  surface: "transparent",
  surfaceMuted: "rgba(255, 255, 255, 0.06)",
  divider: "rgba(255, 255, 255, 0.2)",
  backdrop: "rgba(6, 28, 18, 0.7)",
  modalSurface: "#0F2A1C",
  background: "#0D1C13",
  // hsba(110, 100%, 100%, 0.2) — screen overlays
  overlay: "rgba(43, 255, 0, 0.2)",
} as const;

export const gradientColors = [colors.gradientTop, colors.gradientBottom] as const;

export const fonts = {
  montserratExtraLight: "Montserrat_200ExtraLight",
  montserratRegular: "Montserrat_400Regular",
  montserratMedium: "Montserrat_500Medium",
  montserratBold: "Montserrat_700Bold",
} as const;

export const globalStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  topOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 162,
    backgroundColor: colors.overlay,
    zIndex: 1,
  },
  bottomOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 102,
    backgroundColor: colors.overlay,
    zIndex: 1,
  },
  screenContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 28,
  },
  screenBody: {
    flex: 1,
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
  },
  closeButton: {
    alignSelf: "flex-end",
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  closeButtonText: {
    color: colors.textMuted,
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "300",
  },
  card: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    gap: 16,
    backgroundColor: colors.surface,
  },
  heroTitle: {
    // hsba(0, 0%, 100%, 1)
    color: "hsla(0, 0%, 100%, 1)",
    fontFamily: fonts.montserratBold,
    fontSize: 96,
    lineHeight: 96,
  },
  heroSubtitle: {
    color: colors.text,
    fontFamily: fonts.montserratExtraLight,
    fontSize: 18,
    lineHeight: 22,
    marginTop: 6,
    marginBottom: 20,
  },
  createAccountSubtitle: {
    color: colors.text,
    fontFamily: fonts.montserratExtraLight,
    fontSize: 64,
    lineHeight: 64,
    marginTop: 6,
    marginBottom: 20,
  },
  brandAccent: {
    color: colors.accent,
    fontFamily: fonts.montserratExtraLight,
  },
  brandAccentBold: {
    color: colors.accent,
    fontFamily: fonts.montserratBold,
    fontSize: 96,
    lineHeight: 96,
  },
  brandLogo: {
    alignItems: "center",
    gap: 4,
  },
  brandMark: {
    // hsba(83, 56%, 86%, 1)
    color: colors.buttonText,
    fontFamily: fonts.montserratBold,
    fontSize: 232,
    lineHeight: 232,
    letterSpacing: 0,
    textAlign: "center",
    alignSelf: "center",
  },
  brandName: {
    // hsba(83, 56%, 86%, 1)
    color: colors.buttonText,
    fontFamily: fonts.montserratMedium,
    fontSize: 48,
    lineHeight: 48,
    letterSpacing: 0,
    textAlign: "center",
    alignSelf: "center",
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
  },
  description: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
  },
  field: {
    gap: 8,
    marginBottom: 14,
  },
  fieldRow: {
    flexDirection: "row",
    gap: 12,
  },
  fieldHalf: {
    flex: 1,
  },
  label: {
    color: colors.text,
    fontFamily: fonts.montserratRegular,
    fontSize: 24,
    lineHeight: 28,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 2,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: colors.inputBg,
    color: colors.text,
    fontSize: 16,
  },
  inputWithIcon: {
    paddingRight: 44,
  },
  inputIconButton: {
    position: "absolute",
    right: 12,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    width: 28,
  },
  textArea: {
    minHeight: 120,
    paddingTop: 14,
    textAlignVertical: "top",
  },
  link: {
    color: colors.accent,
    textAlign: "center",
    textDecorationLine: "underline",
  },
  forgotLink: {
    color: colors.accent,
    textDecorationLine: "underline",
    fontSize: 14,
    alignSelf: "flex-start",
    marginTop: -4,
    marginBottom: 8,
  },
  promptRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "auto",
    paddingTop: 24,
  },
  promptText: {
    // hsba(52, 6%, 93%, 1)
    color: colors.buttonBorder,
    fontFamily: fonts.montserratBold,
    fontSize: 32,
    lineHeight: 36,
  },
  promptLink: {
    // hsba(83, 56%, 86%, 1)
    color: colors.buttonText,
    fontFamily: fonts.montserratBold,
    fontSize: 32,
    lineHeight: 32,
    letterSpacing: 0,
    textDecorationLine: "underline",
    textDecorationStyle: "solid",
    textDecorationColor: colors.buttonText,
  },
  primaryButton: {
    borderRadius: 2,
    borderWidth: 3,
    borderColor: colors.buttonBorder,
    borderStyle: "solid",
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    backgroundColor: "transparent",
    marginTop: 8,
  },
  primaryButtonFilled: {
    borderRadius: 2,
    borderWidth: 0,
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    // hsba(83, 56%, 86%, 1)
    backgroundColor: colors.buttonText,
    marginTop: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonText: {
    fontFamily: fonts.montserratRegular,
    fontSize: 48,
    lineHeight: 52,
    color: colors.buttonText,
  },
  primaryButtonFilledText: {
    fontFamily: fonts.montserratRegular,
    fontSize: 48,
    lineHeight: 52,
    color: colors.gradientTop,
  },
  outlineButton: {
    width: "100%",
    height: 133,
    borderWidth: 3,
    borderStyle: "solid",
    // hsba(83, 56%, 86%, 1)
    borderColor: colors.buttonText,
    borderRadius: 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    opacity: 1,
  },
  outlineButtonActive: {
    width: "100%",
    height: 133,
    borderWidth: 3,
    borderStyle: "solid",
    borderColor: colors.buttonText,
    borderRadius: 2,
    alignItems: "center",
    justifyContent: "center",
    // hsba(83, 56%, 86%, 1)
    backgroundColor: colors.buttonText,
    opacity: 1,
  },
  outlineButtonText: {
    // hsba(83, 56%, 86%, 1) — inactive role button label
    color: colors.buttonText,
    fontFamily: fonts.montserratRegular,
    fontSize: 48,
    lineHeight: 48,
    letterSpacing: 0,
  },
  outlineButtonTextActive: {
    color: colors.gradientTop,
    fontFamily: fonts.montserratRegular,
    fontSize: 48,
    lineHeight: 48,
    letterSpacing: 0,
  },
  divider: {
    height: 1,
    backgroundColor: colors.divider,
    marginVertical: 4,
    width: "100%",
    maxWidth: 420,
  },
  appleButton: {
    width: "100%",
    height: 44,
  },
  appleButtonDisabled: {
    opacity: 0.5,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 10,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1.5,
    borderColor: colors.white,
    borderRadius: 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    backgroundColor: "transparent",
  },
  checkboxChecked: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  checkmark: {
    color: colors.gradientTop,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 14,
  },
  checkboxLabel: {
    flex: 1,
    color: colors.textSecondary,
    fontFamily: fonts.montserratExtraLight,
    fontSize: 29,
    lineHeight: 34,
  },
  termsLink: {
    color: colors.accent,
    fontFamily: fonts.montserratExtraLight,
    fontSize: 29,
    lineHeight: 34,
    textDecorationLine: "underline",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: colors.backdrop,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    width: "100%",
    maxWidth: 320,
    backgroundColor: colors.modalSurface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderMuted,
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 16,
    alignItems: "center",
  },
  modalMessage: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    textAlign: "center",
    lineHeight: 26,
  },
  modalButton: {
    alignSelf: "stretch",
    borderWidth: 1,
    borderColor: colors.white,
    borderRadius: 2,
    paddingVertical: 12,
    alignItems: "center",
  },
  modalButtonText: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: "600",
  },
});
