import { StyleSheet } from "react-native";

// Design tokens: colors, layout, spacing, sizes, typography, shadows.
export const colors = {
  inputBg: "rgba(6, 28, 18, 0.55)",
  border: "rgba(255, 255, 255, 0.55)",
  borderMuted: "rgba(255, 255, 255, 0.35)",
  text: "#FFFFFF",
  textMuted: "rgba(255, 255, 255, 0.72)",
  textSecondary: "rgba(255, 255, 255, 0.85)",
  accent: "#C6F54B",
  buttonText: "#ACDB60",
  backArrow: "#ADDC60",
  resetButtonBorder: "#FF0001",
  supportHeader: "#C5BF16",
  supportOkInactive: "#918C11",
  legalLink: "#E2F163",
  inputFill: "#FFFFF1",
  inputText: "#171D1C",
  inputPlaceholder: "#232323",
  white: "#FFFFFF",
  black: "#000000",
  buttonBorder: "#EDEBDF",
  errorBorder: "#A40000",
  surface: "transparent",
  divider: "rgba(255, 255, 255, 0.2)",
  backdrop: "rgba(6, 28, 18, 0.7)",
  modalSurface: "#0F2A1C",
  background: "#171D1C",
  cardSurface: "rgba(255, 255, 255, 0.04)",
  cardBorder: "rgba(255, 255, 255, 0.04)",
  errorCardTint: "rgba(255, 0, 0, 0.04)",
  supportCardTint: "rgba(197, 191, 22, 0.04)",
  successCardTint: "rgba(173, 220, 96, 0.04)",
  genderMale: "#007BEE",
  genderFemale: "#EE00CE",
  sportsExperienceBeginner: "#ADDC60",
  sportsExperienceGymRat: "#5FBFF9",
  sportsExperienceBeastMode: "#FF0001",
  skipLink: "rgba(173, 220, 96, 0.5)",
  shadow: "#000000",
} as const;

export const layout = {
  authMaxWidth: 420,
  authCardBleed: -10,
  authFormSideInset: -8,
  authCardRadius: 30,
  screenPaddingHorizontal: 24,
  appleButtonRadius: 10,
} as const;

export const spacing = {
  authBackTitleDefault: 69,
  authBackTitleSuccess: 109,
  authBackTitleNewPassword: 76,
  authBackTitleWeight: 114,
  authBackTitleAge: 131,
  authBackTitleHeight: 117,
  authBackTitleSupportSubmitted: 97,
  authBackTitleError: 122,
  authBackTitleSupportError: 126,
  authBackTitleContactUs: 110,
  authBackTitleSportsExperience: 60,
  signInHeader: 214,
  signInForm: 60,
  signUpHeader: 80,
  signUpLegal: 45,
  signUpPostHeader: 18,
  forgotPasswordHeader: 217,
  forgotPasswordForm: 202,
  newPasswordHeader: 214,
  newPasswordForm: 117,
  genderHeaderToButtons: 446,
  weightHeader: 194,
  weightUnitToggleScreenInset: 38,
  weightToggleToRuler: 52,
  weightRulerNumberToBar: 5,
  weightRulerToReadout: 5,
  weightRulerReadoutArrowToValue: 19,
  weightRulerReadoutValueLeftGap: 136,
  weightRulerReadoutUnitGap: 4,
  weightReadoutToNext: 38,
  ageReadoutToWheel: 93,
  ageWheelRulerToArrow: 28,
  ageHeaderToSelection: 198,
  ageSelectionToNext: 165,
  heightHeaderToReadout: 67,
  heightRulerNumberToBar: 5,
  heightReadoutToRuler: 16,
  heightRulerNeedlePointerGap: 6,
  heightReadoutToNext: 38,
  genderForm: 94,
  sportsExperienceHeaderToOptions: 199,
  sportsExperienceOptions: 36,
  genderOptions: 65,
  genderOptionsScreenInset: 14,
  successHeader: 302,
  successBody: 206,
  successActions: 18,
  supportResultBody: 216,
  contactUsHeader: 80,
  contactUsForm: 56,
  errorFormActions: 22,
  errorContact: 21,
  fieldStack: 13,
  cardFields: 16,
  socialGroup: 17,
  orSignWith: 11,
  forgotPasswordLink: 12,
  contactHelpTitleBottom: 16,
  cardGap: 14,
  formGap: 14,
  tabContent: 16,
  profileFieldRow: 12,
  safeAreaTopMin: 12,
  safeAreaTopExtra: 4,
  safeAreaBottomMin: 8,
  authSkipLinkVertical: 12,
  authSkipLinkBottom: 6,
  authSkipToNext: 37,
  swipeActiveOffsetX: 20,
  swipeBackTranslation: 72,
  swipeBackFastTranslation: 40,
  swipeBackVelocity: 600,
} as const;

export const sizes = {
  authInputHeight: 45,
  authButtonHeight: 60,
  authButtonPressDuration: 180,
  weightUnitToggleHeight: 60,
  weightRulerStepWidth: 10,
  weightRulerMajorLabelWidth: 104,
  weightRulerMin: 40,
  weightRulerMax: 200,
  weightRulerDefault: 75,
  weightRulerStep: 1,
  weightRulerBarHeight: 87,
  weightRulerNumberRowHeight: 48,
  weightRulerTickMinorHeight: 24,
  weightRulerTickMinorWidth: 1,
  weightRulerTickHalfHeight: 46,
  weightRulerTickHalfWidth: 2,
  weightRulerTickMajorHeight: 46,
  weightRulerTickMajorWidth: 2,
  weightRulerNeedleWidth: 2,
  weightRulerNeedleHeight: 56,
  weightRulerSelectedScale: 1,
  weightRulerAdjacentScale: 1,
  weightRulerFarScale: 1,
  weightRulerAdjacentOpacity: 0.65,
  authReadoutArrowWidth: 46,
  authReadoutArrowHeight: 32,
  authReadoutArrowRadius: 4,
  authReadoutArrowScale: 1,
  weightRulerReadoutUnitOffset: 10,
  ageWheelMin: 13,
  ageWheelMax: 100,
  ageWheelDefault: 28,
  ageWheelSegmentWidth: 70,
  ageWheelSelectionFrameWidth: 87,
  ageWheelBannerHeight: 87,
  ageWheelSelectedBorderWidth: 2,
  ageWheelSelectedLabelNudge: 2,
  ageWheelSelectedScale: 1,
  ageWheelAdjacentScale: 0.86,
  ageWheelAdjacentOpacity: 0.65,
  ageWheelFarOpacity: 0.45,
  ageWheelFarScale: 0.72,
  heightRulerMin: 100,
  heightRulerMax: 250,
  heightRulerDefault: 170,
  heightRulerStep: 1,
  heightRulerStepHeight: 10,
  heightRulerBarWidth: 87,
  heightRulerBarRadius: 10,
  heightRulerNumberColumnWidth: 104,
  heightRulerViewportHeight: 371,
  heightRulerTickMinorWidth: 24,
  heightRulerTickMinorHeight: 1,
  heightRulerTickHalfWidth: 46,
  heightRulerTickHalfHeight: 2,
  heightRulerTickMajorWidth: 46,
  heightRulerTickMajorHeight: 2,
  heightRulerNeedleWidth: 56,
  heightRulerNeedleHeight: 2,
  heightRulerReadoutUnitOffset: 10,
  genderOptionMaleButtonWidth: 189,
  genderOptionButtonHeight: 60,
  signInCardBlurIntensity:15,
  authResultCardHeight: 57,
  successCardIcon: 33,
  contactTextAreaHeight: 235,
  googleIcon: 40,
  backArrowHitSlop: 12,
  backArrowRowMinHeight: 40,
  backArrowRowMarginLeft: 11,
  backArrowTriangleSlotWidth: 12,
  backArrowTriangleSlotHeight: 16,
  backArrowTriangleBorder: 8,
  backArrowTriangleWidth: 12,
  authInputRadius: 15,
  authButtonRadius: 100,
  authCardPaddingTop: 18,
  authCardPaddingBottom: 24,
  authCardPaddingLeft: 24,
  authCardPaddingRight: 26,
  forgotPasswordCardPaddingBottom: 45,
  newPasswordCardPaddingBottom: 39,
  contactUsCardPaddingBottom: 14,
  textAreaPaddingVertical: 12,
} as const;

export const typography = {
  authTitle: {
    fontSize: 20,
    lineHeight: 28,
  },
  authLabel: {
    fontSize: 18,
    lineHeight: 22,
  },
  authSmall: {
    fontSize: 14,
    lineHeight: 18,
  },
  authButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  authInput: {
    fontSize: 16,
    lineHeight: 20,
  },
  authLink: {
    fontSize: 16,
    lineHeight: 20,
  },
  authSkip: {
    fontSize: 15,
    lineHeight: 18,
  },
  weightRulerSelectedNumber: {
    fontSize: 40,
    lineHeight: 48,
  },
  weightRulerAdjacentNumber: {
    fontSize: 35,
    lineHeight: 42,
  },
  weightRulerReadoutValue: {
    fontSize: 64,
    lineHeight: 80,
  },
  weightRulerReadoutUnit: {
    fontSize: 18,
    lineHeight: 22,
  },
  ageWheelSelectedNumber: {
    fontSize: 40,
    lineHeight: 48,
  },
  ageWheelAdjacentNumber: {
    fontSize: 35,
    lineHeight: 35,
  },
  ageWheelFarNumber: {
    fontSize: 25,
    lineHeight: 25,
  },
  ageWheelReadoutValue: {
    fontSize: 64,
    lineHeight: 80,
  },
  heightRulerReadoutValue: {
    fontSize: 64,
    lineHeight: 80,
  },
  sportsExperienceOptionButton: {
    fontSize: 24,
    lineHeight: 28,
  },
} as const;

export const shadows = {
  authCard: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8.1,
    elevation: 4,
  },
} as const;

export const fonts = {
  montserratExtraLight: "Montserrat_200ExtraLight",
  montserratRegular: "Montserrat_400Regular",
  montserratMedium: "Montserrat_500Medium",
  montserratBold: "Montserrat_700Bold",
  poppinsRegular: "Poppins_400Regular",
  poppinsBold: "Poppins_700Bold",
  leagueSpartanLight: "LeagueSpartan_300Light",
  leagueSpartanMedium: "LeagueSpartan_500Medium",
  leagueSpartanBold: "LeagueSpartan_700Bold",
} as const;

const authScreenBase = {
  flex: 1,
  width: "100%" as const,
  maxWidth: layout.authMaxWidth,
  alignSelf: "center" as const,
  minHeight: "100%" as const,
};

const authInputsCardBase = {
  alignSelf: "stretch" as const,
  borderRadius: layout.authCardRadius,
  backgroundColor: colors.cardSurface,
  borderWidth: 1,
  borderColor: colors.cardBorder,
  overflow: "hidden" as const,
  paddingTop: sizes.authCardPaddingTop,
  paddingLeft: sizes.authCardPaddingLeft,
  paddingRight: sizes.authCardPaddingRight,
  paddingBottom: sizes.authCardPaddingBottom,
};

const authBleedStretch = {
  alignSelf: "stretch" as const,
  marginHorizontal: layout.authCardBleed,
};

const supportOkTextBase = {
  ...typography.authTitle,
  fontFamily: fonts.leagueSpartanBold,
  fontWeight: "700" as const,
  textAlign: "center" as const,
  includeFontPadding: false,
};

export const globalStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    flexGrow: 1,
    paddingHorizontal: layout.screenPaddingHorizontal,
    paddingTop: 8,
    paddingBottom: 28,
  },
  screenBody: {
    flex: 1,
    width: "100%",
    maxWidth: layout.authMaxWidth,
    alignSelf: "center",
  },
  tabScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  tabScreenContent: {
    alignItems: "center",
    gap: spacing.tabContent,
  },
  tabScreenText: {
    ...typography.authTitle,
    color: colors.black,
    textAlign: "center",
  },
  profileScreenContent: {
    flex: 1,
    paddingHorizontal: layout.screenPaddingHorizontal,
  },
  profileScreenBody: {
    flex: 1,
    width: "100%",
    maxWidth: layout.authMaxWidth,
    alignSelf: "center",
  },
  profileCard: {
    ...authInputsCardBase,
    backgroundColor: colors.successCardTint,
    gap: spacing.cardFields,
  },
  profileCardFields: {
    gap: spacing.profileFieldRow,
  },
  profileFieldRow: {
    gap: spacing.fieldStack,
  },
  profileFieldLabel: {
    ...typography.authLabel,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    includeFontPadding: false,
  },
  profileFieldValue: {
    ...typography.authInput,
    color: colors.white,
    fontFamily: fonts.montserratRegular,
    fontWeight: "400",
    includeFontPadding: false,
  },
  backArrowRow: {
    minHeight: sizes.backArrowRowMinHeight,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: sizes.backArrowRowMarginLeft,
  },
  backArrowTriangleSlot: {
    width: sizes.backArrowTriangleSlotWidth,
    height: sizes.backArrowTriangleSlotHeight,
    alignItems: "center",
    justifyContent: "center",
  },
  backArrowTriangle: {
    width: 0,
    height: 0,
    borderTopWidth: sizes.backArrowTriangleBorder,
    borderBottomWidth: sizes.backArrowTriangleBorder,
    borderRightWidth: sizes.backArrowTriangleWidth,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderRightColor: colors.backArrow,
  },
  authScreenTitle: {
    ...typography.authTitle,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    flexShrink: 0,
  },
  authScreenTitleTextCenter: {
    textAlign: "center",
  },
  signInScreen: {
    ...authScreenBase,
    gap: spacing.signInForm,
  },
  signInHeader: {
    gap: spacing.signInHeader,
    alignItems: "center",
  },
  signUpScreen: {
    ...authScreenBase,
    gap: spacing.signUpLegal,
  },
  signUpPostHeader: {
    flex: 1,
    gap: spacing.signUpPostHeader,
    alignSelf: "stretch",
  },
  signUpHeader: {
    gap: spacing.signUpHeader,
    alignItems: "stretch",
  },
  forgotPasswordHeader: {
    gap: spacing.forgotPasswordHeader,
    alignItems: "stretch",
  },
  newPasswordHeader: {
    gap: spacing.newPasswordHeader,
    alignItems: "stretch",
  },
  forgotPasswordScreen: {
    ...authScreenBase,
    gap: spacing.forgotPasswordForm,
  },
  forgotPasswordFormContent: {
    ...authBleedStretch,
  },
  newPasswordScreen: {
    ...authScreenBase,
    gap: spacing.newPasswordForm,
  },
  newPasswordFormContent: {
    ...authBleedStretch,
  },
  genderScreen: {
    ...authScreenBase,
  },
  genderHeader: {
    alignItems: "stretch",
  },
  genderHeaderToOptionsGap: {
    height: spacing.genderHeaderToButtons,
    alignSelf: "stretch",
  },
  genderOptions: {
    flexDirection: "row",
    alignSelf: "stretch",
    alignItems: "stretch",
    gap: spacing.genderOptions,
    paddingHorizontal: spacing.genderOptionsScreenInset,
    marginHorizontal: -layout.screenPaddingHorizontal,
  },
  genderOption: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: sizes.genderOptionMaleButtonWidth,
    alignItems: "stretch",
  },
  genderOptionButton: {
    height: sizes.genderOptionButtonHeight,
    width: "100%",
    alignSelf: "stretch",
  },
  genderOptionButtonText: {
    ...typography.authButtonText,
    color: colors.inputFill,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
  },
  genderOptionButtonTextSelected: {
    color: colors.inputText,
  },
  genderOptionMaleSelected: {
    backgroundColor: colors.genderMale,
    borderColor: colors.genderMale,
  },
  genderOptionFemaleSelected: {
    backgroundColor: colors.genderFemale,
    borderColor: colors.genderFemale,
  },
  weightScreen: {
    ...authScreenBase,
  },
  weightHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  weightHeaderToToggleGap: {
    height: spacing.weightHeader,
    alignSelf: "stretch",
  },
  weightUnitToggleWrap: {
    flexShrink: 0,
    marginHorizontal: spacing.weightUnitToggleScreenInset - layout.screenPaddingHorizontal,
  },
  weightUnitToggle: {
    position: "relative",
    flexDirection: "row",
    alignSelf: "stretch",
    height: sizes.weightUnitToggleHeight,
    borderRadius: sizes.authButtonRadius,
    overflow: "hidden",
    backgroundColor: colors.white,
  },
  weightUnitToggleThumb: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: sizes.authButtonRadius,
  },
  weightUnitToggleSegments: {
    flex: 1,
    flexDirection: "row",
    zIndex: 1,
  },
  weightUnitToggleSegment: {
    flex: 1,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  weightUnitToggleLabel: {
    ...typography.authTitle,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.inputPlaceholder,
    includeFontPadding: false,
  },
  weightRulerPicker: {
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "visible",
  },
  weightRulerPickerBody: {
    marginTop: spacing.weightToggleToRuler,
    marginHorizontal: -layout.screenPaddingHorizontal,
    overflow: "visible",
  },
  weightRulerPickerViewport: {
    height:
      sizes.weightRulerNumberRowHeight +
      spacing.weightRulerNumberToBar +
      sizes.weightRulerBarHeight,
    overflow: "visible",
  },
  weightRulerStepColumn: {
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  weightRulerBarSegment: {
    width: "100%",
    backgroundColor: colors.backArrow,
    alignItems: "center",
    justifyContent: "center",
  },
  weightRulerTickMinor: {
    backgroundColor: colors.white,
    opacity: 0.45,
  },
  weightRulerTickHalf: {
    backgroundColor: colors.white,
  },
  weightRulerTickMajor: {
    backgroundColor: colors.white,
  },
  weightRulerNumberLabel: {
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    overflow: "visible",
  },
  weightRulerNumberLabelSlot: {
    position: "absolute",
    top: 0,
    height: sizes.weightRulerNumberRowHeight,
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  weightRulerNeedle: {
    position: "absolute",
    top:
      sizes.weightRulerNumberRowHeight +
      spacing.weightRulerNumberToBar +
      (sizes.weightRulerBarHeight - sizes.weightRulerNeedleHeight) / 2,
    left: "50%",
    width: sizes.weightRulerNeedleWidth,
    height: sizes.weightRulerNeedleHeight,
    marginLeft: -sizes.weightRulerNeedleWidth / 2,
    backgroundColor: colors.black,
    zIndex: 2,
  },
  weightRulerReadout: {
    alignItems: "center",
    marginTop: spacing.weightRulerToReadout,
    gap: spacing.weightRulerReadoutArrowToValue,
    overflow: "visible",
  },
  authReadoutArrow: {
    width: sizes.authReadoutArrowWidth,
    height: sizes.authReadoutArrowHeight,
    alignSelf: "center",
    transform: [{ scale: sizes.authReadoutArrowScale }],
  },
  weightRulerReadoutRow: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "flex-start",
    paddingLeft: spacing.weightRulerReadoutValueLeftGap,
    gap: spacing.weightRulerReadoutUnitGap,
    overflow: "visible",
  },
  weightRulerReadoutValue: {
    ...typography.weightRulerReadoutValue,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    flexShrink: 0,
    overflow: "visible",
  },
  weightRulerReadoutUnit: {
    ...typography.weightRulerReadoutUnit,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    marginBottom: sizes.weightRulerReadoutUnitOffset,
  },
  authFormFooter: {
    alignSelf: "stretch",
    gap: spacing.authSkipToNext,
  },
  authFormFooterButtonRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    alignItems: "stretch",
    paddingHorizontal: spacing.genderOptionsScreenInset,
    marginHorizontal: -layout.screenPaddingHorizontal,
  },
  authFormFooterNextButton: {
    flex: 1,
    height: sizes.authButtonHeight,
    alignSelf: "stretch",
  },
  authFormFooterButtonRowHidden: {
    opacity: 0,
  },
  ageScreen: {
    ...authScreenBase,
  },
  ageHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  ageHeaderToSelectionGap: {
    height: spacing.ageHeaderToSelection,
    alignSelf: "stretch",
  },
  ageWheelPicker: {
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "visible",
  },
  ageWheelReadout: {
    alignItems: "center",
    overflow: "visible",
  },
  ageWheelReadoutBridge: {
    height: spacing.ageReadoutToWheel,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: spacing.ageWheelRulerToArrow,
    overflow: "visible",
  },
  ageWheelReadoutValue: {
    ...typography.ageWheelReadoutValue,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    overflow: "visible",
  },
  ageWheelBanner: {
    marginHorizontal: -layout.screenPaddingHorizontal,
    height: sizes.ageWheelBannerHeight,
    alignSelf: "stretch",
    backgroundColor: colors.backArrow,
    overflow: "hidden",
    position: "relative",
    zIndex: 1,
  },
  ageWheelSegmentSlot: {
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  ageWheelSegmentContent: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  ageWheelSelectionFrame: {
    position: "absolute",
    top: 0,
    borderRadius: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: sizes.ageWheelSelectedBorderWidth,
    borderRightWidth: sizes.ageWheelSelectedBorderWidth,
    borderColor: colors.inputText,
    pointerEvents: "none",
  },
  ageWheelSegmentLabel: {
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    paddingTop: sizes.ageWheelSelectedLabelNudge,
    overflow: "visible",
  },
  heightScreen: {
    ...authScreenBase,
  },
  heightHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  heightRulerPicker: {
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "visible",
  },
  heightRulerReadout: {
    alignItems: "center",
    marginTop: spacing.heightHeaderToReadout,
    overflow: "visible",
  },
  heightRulerReadoutRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: spacing.weightRulerReadoutUnitGap,
    overflow: "visible",
  },
  heightRulerReadoutValue: {
    ...typography.heightRulerReadoutValue,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    flexShrink: 0,
    overflow: "visible",
  },
  heightRulerReadoutUnit: {
    ...typography.weightRulerReadoutUnit,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    color: colors.backArrow,
    includeFontPadding: false,
    marginBottom: sizes.heightRulerReadoutUnitOffset,
  },
  heightRulerPickerBody: {
    marginTop: spacing.heightReadoutToRuler,
    alignItems: "center",
    overflow: "visible",
  },
  heightRulerPickerFrame: {
    position: "relative",
    overflow: "visible",
  },
  heightRulerPickerViewport: {
    overflow: "hidden",
  },
  heightRulerBarTrack: {
    position: "absolute",
    top: 0,
    right: 0,
    width: sizes.heightRulerBarWidth,
    height: sizes.heightRulerViewportHeight,
    borderRadius: sizes.heightRulerBarRadius,
    backgroundColor: colors.backArrow,
    overflow: "hidden",
  },
  heightRulerList: {
    flex: 1,
  },
  heightRulerStepRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  heightRulerBarSegment: {
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  heightRulerTickMinor: {
    width: sizes.heightRulerTickMinorWidth,
    height: sizes.heightRulerTickMinorHeight,
    alignSelf: "center",
    backgroundColor: colors.white,
    opacity: 0.45,
  },
  heightRulerTickHalf: {
    width: sizes.heightRulerTickHalfWidth,
    height: sizes.heightRulerTickHalfHeight,
    alignSelf: "center",
    backgroundColor: colors.white,
  },
  heightRulerTickMajor: {
    width: sizes.heightRulerTickMajorWidth,
    height: sizes.heightRulerTickMajorHeight,
    alignSelf: "center",
    backgroundColor: colors.white,
  },
  heightRulerNumberLabel: {
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    overflow: "visible",
  },
  heightRulerNumberLabelSlot: {
    position: "absolute",
    left: 0,
    height: sizes.weightRulerNumberRowHeight,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  heightRulerNeedle: {
    position: "absolute",
    top: "50%",
    right: (sizes.heightRulerBarWidth - sizes.heightRulerNeedleWidth) / 2,
    width: sizes.heightRulerNeedleWidth,
    height: sizes.heightRulerNeedleHeight,
    marginTop: -sizes.heightRulerNeedleHeight / 2,
    backgroundColor: colors.black,
    zIndex: 2,
  },
  heightRulerNeedlePointer: {
    position: "absolute",
    top: "50%",
    left: "100%",
    marginLeft: spacing.heightRulerNeedlePointerGap,
    marginTop: -(sizes.authReadoutArrowWidth * sizes.authReadoutArrowScale) / 2,
    zIndex: 3,
    overflow: "visible",
  },
  heightRulerNeedlePointerArrow: {
    transform: [{ rotate: "-90deg" }],
  },
  sportsExperienceScreen: {
    ...authScreenBase,
  },
  sportsExperienceHeader: {
    alignItems: "stretch",
    flexShrink: 0,
  },
  sportsExperienceHeaderToOptionsGap: {
    height: spacing.sportsExperienceHeaderToOptions,
    alignSelf: "stretch",
  },
  sportsExperienceOptions: {
    alignSelf: "stretch",
    gap: spacing.sportsExperienceOptions,
    paddingHorizontal: spacing.genderOptionsScreenInset,
    marginHorizontal: -layout.screenPaddingHorizontal,
  },
  sportsExperienceOptionButton: {
    alignSelf: "stretch",
    width: "100%",
  },
  sportsExperienceBeginnerButton: {
    backgroundColor: colors.sportsExperienceBeginner,
  },
  sportsExperienceGymRatButton: {
    backgroundColor: colors.sportsExperienceGymRat,
  },
  sportsExperienceBeastModeButton: {
    backgroundColor: colors.sportsExperienceBeastMode,
  },
  sportsExperienceOptionButtonText: {
    ...typography.sportsExperienceOptionButton,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    color: colors.inputText,
    includeFontPadding: false,
  },
  forgotPasswordInputsCard: {
    paddingBottom: sizes.forgotPasswordCardPaddingBottom,
    backgroundColor: colors.successCardTint,
  },
  newPasswordInputsCard: {
    paddingBottom: sizes.newPasswordCardPaddingBottom,
    backgroundColor: colors.successCardTint,
  },
  successBody: {
    ...authBleedStretch,
    gap: spacing.successBody,
  },
  successActions: {
    alignItems: "center",
    gap: spacing.successActions,
  },
  supportResultBody: {
    ...authBleedStretch,
    gap: spacing.supportResultBody,
  },
  supportErrorOk: {
    ...supportOkTextBase,
    color: colors.backArrow,
  },
  supportSubmittedOk: {
    ...supportOkTextBase,
    color: colors.supportOkInactive,
  },
  errorResultCard: {
    backgroundColor: colors.errorCardTint,
  },
  supportSubmittedCard: {
    backgroundColor: colors.supportCardTint,
  },
  successResultCard: {
    backgroundColor: colors.successCardTint,
  },
  authResultCardShadow: {
    alignSelf: "stretch",
    borderRadius: layout.authCardRadius,
    backgroundColor: colors.background,
    ...shadows.authCard,
  },
  authBlurInputsCardWrap: {
    alignSelf: "stretch",
    borderRadius: layout.authCardRadius,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  authInputsCardShadow: {
    marginHorizontal: layout.authCardBleed,
  },
  errorContact: {
    alignItems: "center",
    gap: spacing.errorContact,
  },
  errorFormActions: {
    alignItems: "center",
    gap: spacing.errorFormActions,
  },
  errorOrText: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  contactUsScreen: {
    ...authScreenBase,
    gap: spacing.contactUsForm,
  },
  contactUsHeader: {
    gap: spacing.contactUsHeader,
    alignItems: "stretch",
  },
  contactUsFormContent: {
    ...authBleedStretch,
  },
  contactUsInputsCard: {
    paddingBottom: sizes.contactUsCardPaddingBottom,
    position: "relative",
    overflow: "visible",
    backgroundColor: colors.supportCardTint,
  },
  contactUsCardIconCorner: {
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 1,
  },
  contactUsCardIconCircle: {
    marginRight: 0,
  },
  contactUsTextArea: {
    height: sizes.contactTextAreaHeight,
    paddingTop: sizes.textAreaPaddingVertical,
    paddingBottom: sizes.textAreaPaddingVertical,
    textAlignVertical: "top",
  },
  contactUsHelpTitle: {
    ...typography.authTitle,
    color: colors.supportHeader,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    marginBottom: spacing.contactHelpTitleBottom,
    textAlign: "center",
    includeFontPadding: false,
  },
  contactUsFieldLabel: {
    color: colors.supportHeader,
  },
  successHeader: {
    gap: spacing.successHeader,
    alignItems: "stretch",
  },
  successCard: {
    alignSelf: "stretch",
    height: sizes.authResultCardHeight,
    borderRadius: layout.authCardRadius,
    backgroundColor: colors.cardSurface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: "visible",
    paddingHorizontal: layout.screenPaddingHorizontal,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  successCardText: {
    ...typography.authTitle,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    textAlign: "center",
    includeFontPadding: false,
    flex: 1,
  },
  authResultIconCircleShadow: {
    width: sizes.authResultCardHeight,
    height: sizes.authResultCardHeight,
    marginRight: -layout.screenPaddingHorizontal,
    borderRadius: sizes.authResultCardHeight / 2,
    backgroundColor: colors.background,
    ...shadows.authCard,
  },
  authResultIconCircleWrap: {
    width: sizes.authResultCardHeight,
    height: sizes.authResultCardHeight,
    borderRadius: sizes.authResultCardHeight / 2,
  },
  successCardIconCircle: {
    width: "100%",
    height: "100%",
    borderRadius: sizes.authResultCardHeight / 2,
    backgroundColor: colors.cardSurface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  successCardIconCircleError: {
    backgroundColor: colors.errorCardTint,
  },
  successCardIconCircleSuccess: {
    backgroundColor: colors.successCardTint,
  },
  successCardIconCircleSupport: {
    backgroundColor: colors.supportCardTint,
  },
  successCardIcon: {
    width: sizes.successCardIcon,
    height: sizes.successCardIcon,
  },
  successCardTextError: {
    color: colors.resetButtonBorder,
  },
  successCardTextSupport: {
    color: colors.supportHeader,
  },
  card: {
    width: "100%",
    maxWidth: layout.authMaxWidth,
    alignSelf: "center",
    gap: spacing.cardGap,
    backgroundColor: colors.surface,
  },
  signUpFormContent: {
    flex: 1,
    ...authBleedStretch,
  },
  signUpInputsCard: {
    ...authInputsCardBase,
    backgroundColor: colors.successCardTint,
  },
  signInInputsCard: {
    alignSelf: "stretch" as const,
    borderRadius: layout.authCardRadius,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: "hidden" as const,
    backgroundColor: "transparent",
  },
  signInInputsCardTint: {
    ...StyleSheet.absoluteFill,
    backgroundColor: colors.successCardTint,
  },
  signInInputsCardContent: {
    paddingTop: sizes.authCardPaddingTop,
    paddingLeft: sizes.authCardPaddingLeft,
    paddingRight: sizes.authCardPaddingRight,
    paddingBottom: sizes.authCardPaddingBottom,
  },
  signInFormContent: {
    flex: 1,
    gap: spacing.orSignWith,
    ...authBleedStretch,
  },
  authInputError: {
    borderWidth: 3,
    borderColor: colors.resetButtonBorder,
  },
  authInputFocused: {
    borderWidth: 3,
    borderColor: colors.backArrow,
  },
  signInSocialGroup: {
    alignItems: "center",
    gap: spacing.socialGroup,
  },
  signInForgotLink: {
    marginTop: spacing.forgotPasswordLink,
    alignSelf: "flex-end",
  },
  signInForgotLinkText: {
    ...typography.authLabel,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    includeFontPadding: false,
  },
  signInOrSignWith: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  signUpInputGroup: {
    gap: spacing.fieldStack,
  },
  signUpCardFields: {
    gap: spacing.cardFields,
  },
  signUpSocialGroup: {
    alignItems: "center",
    gap: spacing.socialGroup,
  },
  authFormField: {
    width: "100%",
  },
  authVideoBackground: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 0,
    overflow: "hidden",
  },
  authVideo: {
    width: "100%",
    height: "100%",
  },
  title: {
    ...typography.authTitle,
    fontWeight: "700",
    color: colors.text,
  },
  description: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 2,
    height: 34,
    paddingHorizontal: 12,
    paddingVertical: 0,
    backgroundColor: colors.inputBg,
    color: colors.text,
    fontSize: 16,
    textAlignVertical: "center",
  },
  signUpInput: {
    height: sizes.authInputHeight,
    backgroundColor: colors.inputFill,
    borderColor: colors.inputFill,
    borderRadius: sizes.authInputRadius,
    color: colors.inputText,
    fontFamily: fonts.poppinsRegular,
    fontWeight: "400",
    ...typography.authInput,
  },
  signUpInputLabel: {
    ...typography.authLabel,
    color: colors.backArrow,
    fontFamily: fonts.leagueSpartanMedium,
    fontWeight: "500",
    marginBottom: 8,
    includeFontPadding: false,
  },
  signUpOrSignWith: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
  },
  signUpLegalText: {
    ...typography.authSmall,
    color: colors.white,
    fontFamily: fonts.leagueSpartanLight,
    fontWeight: "300",
    textAlign: "center",
    includeFontPadding: false,
    marginHorizontal: layout.authCardBleed,
  },
  signUpLegalLink: {
    color: colors.legalLink,
    fontFamily: fonts.leagueSpartanBold,
    fontWeight: "700",
  },
  signUpGoogleButton: {
    alignSelf: "center",
  },
  signUpGoogleIcon: {
    width: sizes.googleIcon,
    height: sizes.googleIcon,
  },
  appButton: {
    alignSelf: "stretch",
    height: sizes.authButtonHeight,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    borderWidth: 3,
    borderColor: colors.backArrow,
    borderRadius: sizes.authButtonRadius,
    overflow: "hidden",
  },
  appButtonText: {
    ...typography.authButtonText,
    fontFamily: fonts.montserratRegular,
    color: colors.inputFill,
  },
  appButtonDisabled: {
    opacity: 0.55,
  },
  signUpLoginLink: {
    marginTop: "auto",
    alignSelf: "center",
  },
  signUpLoginLinkText: {
    ...typography.authLink,
    color: colors.backArrow,
    fontFamily: fonts.poppinsBold,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  authSkipLink: {
    alignSelf: "center",
    paddingTop: spacing.authSkipLinkVertical,
    paddingBottom: spacing.authSkipLinkBottom,
  },
  authSkipLinkText: {
    ...typography.authSkip,
    color: colors.skipLink,
    fontFamily: fonts.montserratMedium,
    fontWeight: "500",
  },
  authSkipFooter: {
    alignItems: "center",
    marginTop: spacing.authSkipToNext,
    paddingHorizontal: layout.screenPaddingHorizontal,
    flexShrink: 0,
  },
  divider: {
    height: 1,
    backgroundColor: colors.divider,
    marginVertical: 4,
    width: "100%",
    maxWidth: layout.authMaxWidth,
  },
  appleButton: {
    width: "100%",
    height: 44,
  },
  appleButtonDisabled: {
    opacity: 0.5,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: colors.backdrop,
    alignItems: "center",
    justifyContent: "center",
    padding: layout.screenPaddingHorizontal,
  },
  modalCard: {
    width: "100%",
    maxWidth: 320,
    backgroundColor: colors.modalSurface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderMuted,
    paddingHorizontal: 20,
    paddingVertical: layout.screenPaddingHorizontal,
    gap: spacing.tabContent,
    alignItems: "center",
  },
  modalMessage: {
    ...typography.authButtonText,
    fontWeight: "700",
    color: colors.text,
    textAlign: "center",
    lineHeight: 26,
  },
  modalButton: {
    alignSelf: "stretch",
    borderWidth: 1,
    borderColor: colors.white,
    borderRadius: 2,
    paddingVertical: sizes.textAreaPaddingVertical,
    alignItems: "center",
  },
  modalButtonText: {
    color: colors.buttonText,
    fontSize: 16,
    fontWeight: "600",
  },
});
